### ISSUE TITLE
Maintain consistency in displaying the countries of the participants in the programs

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#107]
## Description
The names of the countries to which the participants or the mentors for the various programs (eg. Outreachy 2017, GSoC 2010, etc) belong should either be there for all of them, or not be there at all.

## Mocks
![screen shot 2018-03-02 at 9 13 39 am](https://user-images.githubusercontent.com/22029744/36882595-d0296b2a-1dfa-11e8-8a51-9624d4fd4fcf.png)
For example, for Outreachy 2017, in row 2; column 2 the country of the Project maintainer is missing while in row 3; column 2 the country of the mentor is mentioned as USA.

### Update [Required]
- [ ] outreachy/2017.html
- [ ] gsoc/2010.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes.
In case we need to add countries for all the participants, after the information is made available, time estimate is 5 min.

@Janiceilene @MeepyMay @prachi1210 Please assign me the issue, to work upon. Thanks! :)

**Comment by sara-02** [comment]
@BaaniLeen I am not sure about the time estimates, if we are removing the country from all rows then 5 mins is fine, but if one has to search the profiles of the participants and then update the countries then it will be more than 5 mins :)

**Comment by BaaniLeen** [comment]
@sara-02 Do we have a database having the information about all the GSoC or outreachy participants?

**Comment by MeepyMay** [comment]
This is our only database. I'd love to have one and properly show countries here. Can you expand this issue? And add a database?

So adjust this as an enhancement to the project. :) Also, include that in your proposal @BaaniLeen
