### ISSUE TITLE
Consistency in the height of each table data for the various programs

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#108]
## Description
Currently, for the various programs, the table having the details about the participants, mentors, etc does not have cells of consistent heights.

### Buggy Mocks

![screen shot 2018-03-02 at 10 18 58 am](https://user-images.githubusercontent.com/22029744/36885228-c531ad5c-1e0b-11e8-9852-2c5dfcf8a6c6.png)
GSoC 2014

![screen shot 2018-03-02 at 11 25 04 am](https://user-images.githubusercontent.com/22029744/36887980-8b743fa4-1e19-11e8-9c45-1793dbdf04c6.png)
![screen shot 2018-03-02 at 11 25 17 am](https://user-images.githubusercontent.com/22029744/36887985-8f141e68-1e19-11e8-9da7-ccd7e6bfcafe.png)
GSoC 2015

![screen shot 2018-03-02 at 10 18 23 am](https://user-images.githubusercontent.com/22029744/36885176-701eb31e-1e0b-11e8-8eae-94cfac8ce496.png)
GSoC 2013

Similar is the case for the GSoC 2016, GSoC 2017 and Outreachy 2017.

### Corrected Mockups
![screen shot 2018-03-02 at 1 06 25 pm](https://user-images.githubusercontent.com/22029744/36888247-9e746178-1e1a-11e8-8a35-84353850eac6.png)
GSoC 2013

![screen shot 2018-03-02 at 1 06 47 pm](https://user-images.githubusercontent.com/22029744/36888254-a6da47ce-1e1a-11e8-8f83-214b24569dd1.png)
GSoC 2014

Similar corrected mockups exist for all the different program tables.

### Update [Required]
- [ ] stylesheets/styles.css

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 minutes

## Proposed Fix
In line 318 of style.css, add ' height: 4em;'. This would make each of the table data cells to have a height equivalent to the current max height of any cell possible, currently.
@Janiceilene @prachi1210 @MeepyMay Can you please review the issue as well as assign me this issue, so that I can work upon this. :)

**Comment by MeepyMay** [comment]
You're free to work on this @BaaniLeen!
