### ISSUE TITLE
Adding language to .travis.yml

### ISSUE THREAD

**Issue by Tharangi** [systers/systers.github.io#110]
## Description
As a Systers GitHub pages developer,
I need to tell Travis CI that this should be built as a NodeJS project, and the latest version of Node to automatically build pull requests and add outputs to those PRs,
so that I can see if it is safe to merge a request without building it locally.

### Without Specifying the Language - Idetifies the project as a Ruby project
<img width="876" alt="without specifiyng language" src="https://user-images.githubusercontent.com/7287218/36933762-b6edee0a-1f04-11e8-90b9-eb6e05f7a722.png">

### Travis CI integration
 - [ ] Automatically build pull requests without language error.
 - [ ] Automatically add outputs to built PRs without language error.

## Definition of Done
- [ ] All of the required items are completed.

## Estimation
0.25 hours

**Comment by BaaniLeen** [comment]
@Tharangi Would you like to work on this issue? :)

**Comment by akshitac8** [comment]
Hey @Tharangi Is this bug up for solving?
