### ISSUE TITLE
Reducing the gap between social media icons

### ISSUE THREAD

**Issue by Tharangi** [systers/systers.github.io#113]
## Description
As a Systers community member,
I need to see social media icons in the footer without too much of gap in the web version,
so that I can have a better user experience.

#### Existing footer social media icons
![image](https://user-images.githubusercontent.com/7287218/36934926-c0654854-1f16-11e8-90f2-f81371ead14f.png)

#### Suggesting footer social media icons
![socila media icons issue](https://user-images.githubusercontent.com/7287218/36934959-3ff393fa-1f17-11e8-9b8d-f2f917f5b988.png)

### Update [Required]

- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/20111.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ] gsoc/2017.html
- [ ] index.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] Outreachy/2017.html
- [ ] reporting-guidelines.html
- [ ] RGSoC/2018.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by BaaniLeen** [comment]
@Tharangi Would you like to work on this issue?

**Comment by Tharangi** [comment]
@BaaniLeen, you are free to work on this. :)

**Comment by BaaniLeen** [comment]
Thank you @Tharangi ! :)
@Janiceilene @prachi1210 Can you please assign me this issue? :)

**Comment by BaaniLeen** [comment]
@prachi1210 @Janiceilene Please review the Pull Request for this issue. Also, instead of making the changes in all the HTML files, as mentioned in the issue, I made changes in the Stylesheet to reflect the change for all the webpages.
Thanks! :)

**Comment by Tharangi** [comment]
Good work, @BaaniLeen. Did you check how icons look on mobile versions as well after your change?

**Comment by BaaniLeen** [comment]
@Tharangi Thanks alot! No, I could not since the current version of code in the repo is not hosted anywhere as of now. Can you please guide me as to how to go about checking it for the mobile version? :)

**Comment by Janiceilene** [comment]
@BaaniLeen Do you have the Development tools enabled on Safari?  Or use the Dev tools in Chrome?  That's how I've been checking various screen sizes.

**Comment by BaaniLeen** [comment]
@Janiceilene Sure! Thanks alot. Will try the same and let you know! :)

**Comment by divyanshu-rawat** [comment]
Hi @BaaniLeen 
You can make use Chrome DevTools' Device Mode for build mobile-first, fully responsive websites.
You can Emulate your site across different screen sizes and resolutions.
Toggle the Device Mode button to turn Device Mode on or off.
You can also toggle Device Mode by pressing Command+Shift+M (Mac) or Ctrl+Shift+M (Windows, Linux).
Please find attached screenshot for more details.

![screen shot 2018-03-05 at 10 42 39 am](https://user-images.githubusercontent.com/13464678/36968163-fccf153a-2061-11e8-8312-740b82197ecc.png)

**Comment by Tharangi** [comment]
@BaaniLeen, I assume that you got the answer from above two comments.

**Comment by BaaniLeen** [comment]
@Tharangi @divyanshu-rawat Can we close this issue now?
