### ISSUE TITLE
Changing the social media icons to equal-sized icons

### ISSUE THREAD

**Issue by Tharangi** [systers/systers.github.io#114]
## Description
As a Systers community member,
I need to see social media icons in the footer as an equal-sized icon set,
so that I can have a better user experience.

#### Existing social media icons
![image](https://user-images.githubusercontent.com/7287218/36935108-07881782-1f19-11e8-8bc6-98f0e8d6ad81.png)

#### Suggesting appearance
![socila media icons issue2](https://user-images.githubusercontent.com/7287218/36935422-9d88bcf6-1f1d-11e8-8d43-515944ce94df.png)

### Update [Required]
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/20111.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ] gsoc/2017.html
- [ ] index.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] Outreachy/2017.html
- [ ] reporting-guidelines.html
- [ ] RGSoC/2018.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by BaaniLeen** [comment]
@Tharangi I am unable to replicate the issue. In the given current scenario screenshot too, the social media icons seem to be of the same size only.
Can you please help me understand the issue you are facing, better?

**Comment by Tharangi** [comment]
Sure. Let's see the sizes of the existing icons. 

- Twitter icon: 400 x 400 px
- Facebook icon: 100 x 100 px
- Youtube icon: 734 x 518 px
- Medium icon: 390 x 390 px
- Blogger icon: 64 x 64 px

So what I am suggesting is to use equal-sized icons, i.e. 48 x 48 px **_OR_** 64 x 64 px icons for all social media icons. 

Is it clear to you now?

**Comment by BaaniLeen** [comment]
Oh okay! Thats a great observation! :)
Thanks :)

**Comment by BaaniLeen** [comment]
@Tharangi I would suggest that instead of using the image tag to place images of the symbols for social media contact icons, we use Font Awesome icons, instead! :)
What are your views upon it? Can I go ahead and work on this issue? :)

**Comment by Tharangi** [comment]
Yeah, we can do that, I prefer using coloured icons though. Anyways I will attach here the icon images I used in the mockup. There are available to download from [here](https://www.iconfinder.com/iconsets/social-network-24). 
![if_twitter_2460210](https://user-images.githubusercontent.com/7287218/36943038-f2ce1ac8-1fa7-11e8-9889-8bb147d9795d.png)
![if_blogger_2460209](https://user-images.githubusercontent.com/7287218/36943039-f4426094-1fa7-11e8-953c-9fc588cb850b.png)
![if_facebook_2460233](https://user-images.githubusercontent.com/7287218/36943040-f59b430c-1fa7-11e8-8d7e-9c4fb1c63fab.png)
![if_youtube_2460230](https://user-images.githubusercontent.com/7287218/36943044-fef41b86-1fa7-11e8-9893-38ab87472287.png)
![if_medium_2460232](https://user-images.githubusercontent.com/7287218/36943045-0095306a-1fa8-11e8-9db9-5bff731bfcaf.png)
Ofcourse, you can work on this issue.

**Comment by BaaniLeen** [comment]
@MeepyMay @prachi1210 Please assign me this issue. :)

**Comment by divyanshu-rawat** [comment]
@BaaniLeen you can also make use of bootstrap glyphicons
@Tharangi even we can assign colors to font-awesome icons as well.
