### ISSUE TITLE
move "contact us" links as icons to "find us at"

### ISSUE THREAD

**Issue by ancyp** [systers/systers.github.io#115]
## Description
As a user of the website, it is confusing to see 2 sections - "contact us" and "find us at".
Moreover "Contact us"- Slack, github, mailing list -  is hidden away under "about us". The relevant icons can be directly added to the other social media icons in the footer, so that  I have easier access to contacts. 

### Update [Required]
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/20111.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ]  gsoc/2017.html
- [ ] index.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] Outreachy/2017.html
- [ ] reporting-guidelines.html
- [ ] RGSoC/2018.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 minutes

**Comment by divyanshu-rawat** [comment]
@ancyp you have written index.html and contactus.html twice please remove the duplicates 👍

**Comment by akshitac8** [comment]
Hello,
Is this bug open for solving?

**Comment by ancyp** [comment]
yes @akshitac8

**Comment by divyanshu-rawat** [comment]
@akshitac8 yes, it is 👍

**Comment by sara-02** [comment]
@ancyp While I agree that we currently have 2 points of contact, plus a join the slack section but let's take a moment to understand why we those two separate sections. The find us section with all the social media icons is more for following the Syster's activity. Think of it this way, if you like a page on fb, you don't necessarily contribute to that page or the org, you just follow it because you are interested in the content they post, which might be useful in your field. But when you are contributing on Github, or joining a slack community it calls for a more active participation from your side. Then you are not just consuming a news feed but actively engaging in community work, through issues, PR, Q/A etc. 
Maybe we can better word these two sections to something like `Participate in the community` and `Follow us on`, instead of simply moving all icons under one hood as those serve different purposes.

**Comment by sara-02** [comment]
IHMO this requires for a deeper discussion and we need to have mock ups with new icon placements approved before taking up this issue.
@divyanshu-rawat @Janiceilene @MeepyMay

**Comment by sara-02** [comment]
@jericahuang @akshitac8 please share your design ideas and mocks here or in the PR you have created/want to create.

**Comment by divyanshu-rawat** [comment]
@sara-02 I agree with you on this "Maybe we can better word these two sections to something like Participate in the community and Follow us on, instead of simply moving all icons under one hood as those serve different purposes."
Let's wait for @MeepyMay @Janiceilene Opinion 👍

**Comment by jericahuang** [comment]
Here's a screenshot of what the FA icons will look like. You can specify their color (like you can with text, even change their color when hovering/clocking) and another advantage is that they load faster than images.
<img width="1399" alt="screen shot 2018-03-23 at 12 32 24 pm" src="https://user-images.githubusercontent.com/8077898/37841555-63b86afc-2e96-11e8-826a-5ed4c59e1587.png">

**Comment by jericahuang** [comment]
I agree about separating them into two sections "Participate in the community" and "Follow us on"

**Comment by Janiceilene** [comment]
I don't mind using Font Awesome icons, but the number of icons at the bottom of your screenshot is overwhelming.  We'd definitely need to have a discussion about what the purpose of the bottom section is and what should be included there versus in the Contact Us section.

**Comment by akshitac8** [comment]
Great Work @jericahuang . I agree that we can use font awesome icons for this. I think, we can have something like `#1a237e` as the color for the icons. Also, the 5 icons looks best when seen at desktop as well as mobile versions. We can add **Slack**, **Github** and **Email** in a separate line by giving simple links.

**Comment by akshitac8** [comment]
Hey @divyanshu-rawat  I suppose this one was [assigned](https://github.com/systers/systers.github.io/issues/115#issuecomment-373843468) to me. I have made a [working demo](https://systers.herokuapp.com/issue115/). Please review.

**Comment by ancyp** [comment]
@divyanshu-rawat did we agree on having 2 sections?

@akshitac8 You need to comment saying you are working on it I believe - which is why there are 2 people now working on the same thing.
The colors need to be changed .. All blue doesn't look good.

**Comment by Janiceilene** [comment]
@divyanshu-rawat @ancyp Discussion is still ongoing.  I think many things about the navigation will change as we increase the functionality on the site.

**Comment by BaaniLeen** [comment]
@ancyp @Janiceilene Can we close this?
