### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by ancyp** [systers/systers.github.io#116]
## Description
As a user of the webpage, I'd like to be able to view the page faster.
Applying these optimizations may improve the speed of this page:
**Minify CSS:** Compacting CSS code can save many bytes of data and speed up download and parse times.
**Optimize images:** Properly formatting and compressing images can save many bytes of data.
Check the following link to get a direct link to download,  ready-to-use optimized CSS and image files.
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fsysters.io&tab=desktop

### Update [Required]
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/20111.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ] gsoc/2017.html
- [ ] index.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] Outreachy/2017.html
- [ ] reporting-guidelines.html
- [ ] RGSoC/2018.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Saichethan** [comment]
@ancyp  Google insight will do that, but for any working directory it's not preffered to optimize content. 
That's a good idea but should only be helpful once there are no more further commits

**Comment by divyanshu-rawat** [comment]
@Saichethan @ancyp We can make use of [Google Page Insights](https://developers.google.com/speed/pagespeed/insights/) to get insights about page performance and for minification and concatenation, we can make use of Gulp or Grunt to automate and facilitate the process.

**Comment by Saichethan** [comment]
@divyanshu-rawat as this website is not fully developed and it would be developed by end of summer(GSoC) so, till that point of time minifying CASE or JS leads to confusions so, I would say do that once this project is done!
Correct me if I am wrong!

**Comment by Saichethan** [comment]
@divyanshu-rawat as this website is not fully developed and it would be developed by end of summer(GSoC) so, till that point of time minifying CSS or JS leads to confusions so, I would say do that once this project is done!
Correct me if I am wrong!

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
