### ISSUE TITLE
About us tab irrelevance

### ISSUE THREAD

**Issue by ancyp** [systers/systers.github.io#117]
## Description
As a user of the website, I would prefer the links under "About us" - code of conduct and reporting guidelines to be under "Others" or in the footer like in https://ghc.anitab.org/ or as links in text under "Welcome to Systers' Open Source!" section of home page, so that  I do not find a irrelevance of the same.

### Update [Required]
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/20111.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ] gsoc/2017.html
- [ ] index.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] Outreachy/2017.html
- [ ] reporting-guidelines.html
- [ ] RGSoC/2018.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Vertika-Shukla** [comment]
@ancyp I want to work on this.

**Comment by divyanshu-rawat** [comment]
@ancyp You have written the index.html twice please remove the duplicate.

**Comment by ancyp** [comment]
@Vertika-Shukla can you please submit a PR with screenshots ?

**Comment by Vertika-Shukla** [comment]
@ancyp I have already added a screenshot in my PR. Please have a look.

**Comment by ancyp** [comment]
correct me if I am wrong @divyanshu-rawat, the student has to reference the PR ?
I can only see the student's commit on forked version here!

**Comment by BaaniLeen** [comment]
@ancyp Yes. The PR needs to be referenced :)
@Vertika-Shukla Please create a pull request and reference it with the issue for the mentors to review. Thanks! :)

**Comment by divyanshu-rawat** [comment]
Yes, @ancyp PR needs to be referenced.
@Vertika-Shukla please create a pull request and reference it 👍

**Comment by BaaniLeen** [comment]
@ancyp Since the PR was closed by Janice, can we close this issue now?
