### ISSUE TITLE
Removing redundant code for header and footer

### ISSUE THREAD

**Issue by ancyp** [systers/systers.github.io#118]
## Description
As a contributor, I would prefer to use a common html file for header and footer instead of  redundantly using  these snippets  in multiple html files, so that I do not need to modify multiple files to do a change in header/footer.

 This can be avoided by jQuery or pure Javascript.
https://stackoverflow.com/questions/44502243/single-navigation-bar-across-website

### Update [Required]
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ]  gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/20111.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ] gsoc/2017.html
- [ ] index.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] Outreachy/2017.html
- [ ] reporting-guidelines.html
- [ ] RGSoC/2018.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by shreyateeza** [comment]
@ancyp Please update the Description. Write as per the template.

**Comment by divyanshu-rawat** [comment]
@ancyp redundancy can also be removed by relying on a client-side library like react or client-side framework angular.js or to be more precise by building an SPA because as far as I know, JQuery is bit old now to work on.

**Comment by BaaniLeen** [comment]
@ancyp @divyanshu-rawat Can we close this issue now, since we are incorporating this in the new codebase? :)

**Comment by sara-02** [comment]
@BaaniLeen Can you refer this issue in the new codebase PR.`Fixes #issuenumber` should automatically close this issue once the new code PR is merged.
If it is already merged, then add a comment here with the PR link, so that we have a reference for it. And then, of course, we should close it :)

**Comment by BaaniLeen** [comment]
Done! Thanks @sara-02 :)
