### ISSUE TITLE
Improper Indentation under systers weekly updates in contactus

### ISSUE THREAD

**Issue by ancyp** [systers/systers.github.io#120]
## Description
As a user of the webpage, I would like to see Phone numbers in line with paragraph, so that it is visually pleasing to the eye.

### Update [Required]
- [ ] contactus.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by shreyateeza** [comment]
@ancyp Please update the Description. Write as per the template.

**Comment by divyanshu-rawat** [comment]
Ya, I agree with you on this 👍 
@sara-02 and @shreyateeza I guess this is an issue that'a need to be resolved what do you think?
I have attached the screenshot visually showing issue created by @ancyp  
![screen shot 2018-03-05 at 11 32 28 am](https://user-images.githubusercontent.com/13464678/36970451-f0b6e3f2-2068-11e8-9e58-f66914b173ab.png)

**Comment by sara-02** [comment]
@ancyp @divyanshu-rawat feel free to add a PR for this :)

**Comment by krishnan2098** [comment]
Is this resolved? Otherwise, Can I work on this?

**Comment by divyanshu-rawat** [comment]
@krishnan2098 it is resolved now 👍
