### ISSUE TITLE
Add Description of the Open Source Internships

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#122]
## Description
As a Syster community member,
I need to add the following-

1. Description of the open source internships like GSoC, RGSoC, etc.
2. Mention who can participate in these like Female, Male or Both.
3. Provide links to their respective pages.

so that I can help newcomers have better user experience.

## Mocks
![gsoc](https://user-images.githubusercontent.com/30488330/36937454-7312f182-1f39-11e8-82fd-f58e452b5af3.png)

### Update [Required]
- [ ] index.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes

**Comment by amanvats** [comment]
I would like to work on this. Can I?

**Comment by shreyateeza** [comment]
@amanvats Sure! Go ahead. :+1:

**Comment by divyanshu-rawat** [comment]
@shreyateeza Nice I agree with you on the same 👍

**Comment by amanvats** [comment]
This is my first contribution to open source. I have opened a pull request. Please let me know about my mistakes and ways to improve. Thanks.

**Comment by aayushinigam** [comment]
I would like to work on this issue. Is it still open?

**Comment by divyanshu-rawat** [comment]
@aayushinigam @amanvats has already sent the PR for the same which is still open.
@amanvats what's the status of your PR?

**Comment by amanvats** [comment]
Initially, my PR had merge conflicts. I have fixed that and have asked the community for review.

**Comment by divyanshu-rawat** [comment]
@amanvats cool 👍 
@aayushinigam PR is still under review.

**Comment by drashti4** [comment]
Is this issue still WIP?

**Comment by BaaniLeen** [comment]
@Janiceilene @ancyp Can we close this issue? Resolved in #240 .
