### ISSUE TITLE
Update framework/language used for each project

### ISSUE THREAD

**Issue by kanmodi** [systers/systers.github.io#126]
## Description
As a Syster community member,
I need the following technologies/frameworks used in each project to be added in brackets.

## Mocks
Current
![image](https://user-images.githubusercontent.com/17910094/36948868-e0ab3268-2006-11e8-9662-fd4923dbe5a0.png)
Required
![image](https://user-images.githubusercontent.com/17910094/36948904-579ba60a-2007-11e8-9316-660a7753b0a0.png)

### Update [Required]
- [ ] index.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15 minutes

**Comment by isunitha98selvan** [comment]
I would like to work on this.

**Comment by BaaniLeen** [comment]
Will be covered in Issue #190
