### ISSUE TITLE
Fix Broken Link

### ISSUE THREAD

**Issue by divyanshu-rawat** [systers/systers.github.io#136]
## Description
As a User, I need to fix the broken link, So that I can enrich the user experience.
Fix broken link in member-levels.html Line 147 which is pointing to [](http://localhost:8001/index.html/#programs)

## Mocks
![screen shot 2018-03-05 at 11 57 13 pm](https://user-images.githubusercontent.com/13464678/37004627-526b5552-20d1-11e8-93d6-323b135a569f.png)

### Update [Required]
- [ ] File member-levels.html Line 147

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10-20 Minutes

**Comment by divyanshu-rawat** [comment]
Hi, @akshitac8 ya it was a bug but it's resolved now.

**Comment by MeepyMay** [comment]
Resolved, so closing issue.

**Comment by divyanshu-rawat** [comment]
@MeepyMay it's still not resolved I am reopening the issue.
