### ISSUE TITLE
target of some links should be in new tab

### ISSUE THREAD

**Issue by santosh62** [systers/systers.github.io#140]
## Description
After clicking the all links of years of systers with GSoC and all the social links given at the footer it opens in same tab instead  of opening in new tab 

## Mocks

![1](https://user-images.githubusercontent.com/29174089/37037079-8b2962ac-2177-11e8-8322-64d152cdb967.png)
after clicking at``` 2017```
it opens in same tab
![2](https://user-images.githubusercontent.com/29174089/37037077-8ace5ee8-2177-11e8-9e43-cfcb0ac8ef41.png)
it should be open in ```new tab```
![3](https://user-images.githubusercontent.com/29174089/37037076-8ab1bfb8-2177-11e8-8f7a-0a977b9e82f1.png)

## Acceptance Criteria
the target of links should be the ```new tab```

### Update [Required]
- [x] index.html

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by Paarmita** [comment]
@santosh62 Can I work on this?

**Comment by santosh62** [comment]
sorry @Paarmita  i'm working on this 
i'm waiting for the ```mentors```` approval to pull request .

**Comment by Janiceilene** [comment]
The links that point to an internal page, like the program tables should open in the same tab. The social media links should open in a new tab.

**Comment by santosh62** [comment]
So should u work on only social media links?

**Comment by divyanshu-rawat** [comment]
Ya, I agree with @Janiceilene on this 👍

**Comment by MeepyMay** [comment]
As @Janiceilene mentioned, it's an internal page. If you would like to work on the social media links, please update this issue to reflect as such. This is an enhancement. Please note that in the "Enhancement to Update" area in the issue template.
