### ISSUE TITLE
smooth scrolling to the same page links ( nav-bar links).

### ISSUE THREAD

**Issue by santosh62** [systers/systers.github.io#145]
## Description
As a user of the website, I'd like to have a smooth UX when i click on the on page anchor links (from nav-bar link eg.``` Join Systers``` , ``` projects``` , ``` Programms```).
Right now, link in the nav-bar to an anchor in the current page causes a jump scroll.

here is the sample pen of smooth scrolling effect .

https://codepen.io/santosh62/full/mxbbQv/

using this we can achieve  smooth scrolling without any change in UI.

### Update [Required]
- [ ] index.html
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/20111.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ] gsoc/2017.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] Outreachy/2017.html
- [ ] reporting-guidelines.html
- [ ]  RGSoC/2018.html
 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
 1 hours

**Comment by santosh62** [comment]
@MeepyMay  @Janiceilene @divyanshu-rawat
should i work on this??

**Comment by MeepyMay** [comment]
Please update this issue. Similar comments as issue #148
