### ISSUE TITLE
 Drop down show/hide onclick on mobile devices - need to hide when clicking outside or on menu header

### ISSUE THREAD

**Issue by AnkitKhatri55555** [systers/systers.github.io#149]
## Description
In mobile devices,  Drop down menu should function as show/hide on click - need to hide when clicking outside or on the same menu header itself, to make it easier for the user.

## Mocks
![screen shot 1939-12-21 at 10 40 47 pm](https://user-images.githubusercontent.com/36541665/37298515-7ae2f042-2646-11e8-8976-e6941f746288.png)

## Acceptance Criteria
The drop down menu should hide/show on click or tap on mobile devices.
### Update [Required]
-A jquery file can be created to have this functionality

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
 30 min

**Comment by Vertika-Shukla** [comment]
@AnkitKhatri55555 I want to work on this.

**Comment by AnkitKhatri55555** [comment]
sure @Vertika-Shukla

**Comment by shreyateeza** [comment]
@divyanshu @Vertika-Shukla @AnkitKhatri55555 an issue related to this one has already been created.
Check https://github.com/systers/systers.github.io/issues/65

**Comment by AnkitKhatri55555** [comment]
@shreyateeza , I think the issue you created was that the drop down menu hides the content below it.This one is just for hide/show on click purpose

**Comment by MeepyMay** [comment]
Please use #65 to include all errors in the DropDown Menu.
