### ISSUE TITLE
Orientation Materials

### ISSUE THREAD

**Issue by ExactlyMay** [systers/systers.github.io#151]
## Description
As a newcomer,
I need additional information,
so that I understand Systers Open Source.

## Mocks
Use [Public Lab](https://publiclab.github.io/community-toolbox/) for reference to update our [Newcomers](http://systers.io/newcomers) page. 

### Update [Required]
- [ ] Mock/Design for the updated Newcomers page.
- [ ] GitHub Issue integration that has live changes when new issues are labeled. (Use Public Lab's community toolbox.)

### Enhancement to Update [Optional]
- [ ] Include sections of non-coding and coding related contributions. (What does it look like if someone wanted to only contribute documentation? Or only contribute designs?)
- [ ] Filter/search based on labels. 
- [ ] Add contributors section at the bottom.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Follow AnitaB.org Brand guidelines.
- [ ] Approval by 1 mentor.

## Estimation
20 hours

**Comment by Saichethan** [comment]
Can mock be a photo copy of design hand drawn?

**Comment by manishakeim** [comment]
@Saichethan For mock-up designs, you can use Invisionapp or Photoshop to design them.

**Comment by divyanshu-rawat** [comment]
@Saichethan even you can make use of framer or UX-pin as they offer more capabilities in comparison to that of invisionapp.

**Comment by divyanshu-rawat** [comment]
@Saichethan are you working on this?

**Comment by shreyateeza** [comment]
@divyanshu-rawat Can I work on this issue?

**Comment by shreyateeza** [comment]
@divyanshu-rawat This issue has label 'Program:GSOC'. Can I still work on this?
If not then please unassign me.

**Comment by BaaniLeen** [comment]
@shreyateeza It will be worked upon during GSOC :)
