### ISSUE TITLE
Workflow Graph

### ISSUE THREAD

**Issue by ExactlyMay** [systers/systers.github.io#152]
## Description
As an open source contributor,
I need learn how Systers Open Source develops their applications,
so that I can submit my first PR!

## Mocks
Use the current [version 1.0](http://systers.io/open-source-workflow) to help guide you through the details.

### Update [Required]
- [ ] Create a mock/design for the updated Workflow page.
- [ ] Includes all stages of the development lifecycle (5 Stages: Requirements Analysis, Design, Development & Testing (TDD), Testing, Maintenance).
- [ ] Include examples in each stage.

### Enhancement to Update [Optional]
- [ ] Make the graph interactive.
- [ ] Use modal windows to include additional details of each stage.
- [ ] Add your own creative idea.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Follow AnitaB.org Brand guidelines.
- [ ] Approval by 1 mentor.

## Estimation
30 hours

**Comment by isunitha98selvan** [comment]
I would like to work on this.

**Comment by prithaupadhyay** [comment]
Can I work on this? I'll start by creating mocks for the workflow graph after your approval.

**Comment by manishakeim** [comment]
@isunitha98selvan @prithaupadhyay You both can start with designing mocks and show it on slack channel and we will discuss further.

**Comment by prithaupadhyay** [comment]
@manishakeim  I have designed a mockup for the Workflow graph and I have shared it in the #ideas channel. I would love to receive your suggestions over that design.

**Comment by eva-ave** [comment]
Hi, is this issue still looking for new contributors? :)

**Comment by eva-ave** [comment]
Nah just here to help out! Ok I'll check it out on slack! Thanks alot @sara-02 !

**Comment by divyanshu-rawat** [comment]
@isunitha98selvan , @prithaupadhyay are both of you still working on this issue?
