### ISSUE TITLE
Contributor Recognition

### ISSUE THREAD

**Issue by divyanshu-rawat** [systers/systers.github.io#153]
## Description
As an open source Systers contributor,
I want to be recognized for my contribution.

## Mocks
Use [Coala's](https://coala.io/#/getinvolved) for reference.

### Update [Required]
- [ ] Mock/Design for the New page.
### Enhancement to Update [Optional]
- [ ] Filter/search contributors.
- [ ] Short Bio of every contibutor.
- [ ] Add your own creative idea.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.
- [ ] Follow AnitaB.org Brand guidelines.

## Estimation
30 hours

**Comment by sara-02** [comment]
@divyanshu-rawat if I am not wrong then @BaaniLeen already had some ideas and mocks-ups around the same issue.

**Comment by divyanshu-rawat** [comment]
@sara-02 then what to do?

**Comment by sara-02** [comment]
@divyanshu-rawat I don't think any issue was created for it previously. I just remember the mocks from the slack discussion. So let this issue be, who so ever works on it, can coordinate with you and Baani :)

**Comment by sara-02** [comment]
Also, you can add the appropriate tags for GSOC, and difficulty level

**Comment by BaaniLeen** [comment]
[Mockups_Meet_Us_V1.pdf.pdf](https://github.com/systers/systers.github.io/files/1806692/Mockups_Meet_Us_V1.pdf.pdf)
@divyanshu-rawat These were the mock-ups suggested by me on slack. Feel free to give suggestions regarding the same! :)

**Comment by divyanshu-rawat** [comment]
@BaaniLeen LGTM but what I think you can still improve the user-interface design proposed by you for inspiration you can have look on [coala](https://coala.io/#/getinvolved) page.
And do you think that is there a point of adding LinkedIn because this is about contributor recognition not about connecting with the contributors.
Correct me if I am wrong somewhere.
what do you think @sara-02 ?

**Comment by sara-02** [comment]
Github is needed for sure. Apart from that other links are not so necessary. If I want I can volunteer to share my Linkedln, blog, or email. But Having only GitHub should do :)

**Comment by BaaniLeen** [comment]
@divyanshu-rawat Please have a look at the discussion done on slack! You can add your ideas to the thread and get feedback from the mentors on the same :)

**Comment by divyanshu-rawat** [comment]
Ya but @BaaniLeen feel free to add your ideas but not everyone is willing to share their LinkedIn profile due to privacy reasons that's what I am saying 👍 .

**Comment by Vertika-Shukla** [comment]
@divyanshu-rawat Can I work on this?

**Comment by divyanshu-rawat** [comment]
@Vertika-Shukla, @BaaniLeen is already working on this I guess? 
@BaaniLeen are u working on this?

**Comment by Vertika-Shukla** [comment]
@divyanshu-rawat I have also started working on this for GSOC
Do I need to switch now?

**Comment by sara-02** [comment]
@Vertika-Shukla Are you submitting a PR currently or putting it as  part of GSoC proposal.

**Comment by Vertika-Shukla** [comment]
@sara-02 I am putting it as a part of GSOC

**Comment by sara-02** [comment]
No issues then, you can add it to your proposal, just don't copy-paste Bani's solution, add your creative to it :)

**Comment by BaaniLeen** [comment]
@Vertika-Shukla You are free to come up with your mockups for the same and discuss it with the mentors preferably, before your start to code, as suggested by @MeepyMay. :)

**Comment by Vertika-Shukla** [comment]
@sara-02 @BaaniLeen I am working on the mockup for this. Will discuss with mentors on slack soon.

**Comment by divyanshu-rawat** [comment]
@Vertika-Shukla are u still working on this? if yes then I can assign this issue to you.

**Comment by Vertika-Shukla** [comment]
@divyanshu-rawat I was working on this for GSoC so created the mocks for this issue. As told earlier that baani is working on this so didn't started to work for PR. 
If now Baani is not working on this, I am then open to take up this issue. You can assign this to me.

**Comment by BaaniLeen** [comment]
@divyanshu-rawat As discussed on slack, this is one of the tasks to be done during GSoC. So, I was suggested by Prachi & May to create the mockups and have a discussion regarding the implementation but start with the coding only during the GSoC period after finalising upon the final Mockup! :)

**Comment by divyanshu-rawat** [comment]
cool got it @BaaniLeen let's wait then until GSOC period.
Although, is the final mockup ready?

**Comment by Vertika-Shukla** [comment]
@divyanshu-rawat @BaaniLeen sounds cool. Let's wait then
