### ISSUE TITLE
Celebration Page

### ISSUE THREAD

**Issue by divyanshu-rawat** [systers/systers.github.io#154]
## Description
As an open source Systers community member,
I want to know about the upcoming events organized by the AnitaB.org Local community members and how to join them.

## Mocks
- [ ] Create a mock/design for the page including Google calendar.
- [ ] Use [Community](https://community.anitab.org/) for reference.

### Update [Required]
- [ ] Overview of systers communities
- [ ] Google calendar integration that shows upcoming events and "About Us" or "Contact Us" needs to 
        be included.
- [ ] No embedding of Google Calendar.
- [ ] Overview of joining AnitaB.org events in your area.
 
### Enhancement to Update [Optional]
- [ ] Add your own creative idea.
- [ ] Sort/Filter and find upcoming events.
- [ ] Meet and connect with the community for reference please visit [community members](https://community.anitab.org/members/)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Follow AnitaB.org Brand guidelines.
- [ ] Approval by 1 mentor.

## Estimation
 3-4 Days

**Comment by BaaniLeen** [comment]
@divyanshu-rawat Kindly see the repo systers/celebrations, and the issues enlisted there.
This is a duplicate issue. :)
Kindly close this issue.

**Comment by divyanshu-rawat** [comment]
@BaaniLeen Ya, Thanks 👍
