### ISSUE TITLE
Link to contact us page contains .html extension in url

### ISSUE THREAD

**Issue by Vertika-Shukla** [systers/systers.github.io#162]
## Description
Link to contact us page http://systers.io/contactus.html This url contains .html extension which is not a good practice. **.html** should be removed from url.

## Mocks
![image](https://user-images.githubusercontent.com/32086233/37902521-4c068956-3112-11e8-8a68-6704f23cdbc2.png)

## Acceptance Criteria
index.html should be modified accordingly

### Update [Required]
- [ ] index.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by Vertika-Shukla** [comment]
Can I work on this?

**Comment by sara-02** [comment]
@Vertika-Shukla this doe not look like a duplicate, so you can work on it.

**Comment by divyanshu-rawat** [comment]
@Vertika-Shukla issue assigned to you 👍

**Comment by Vertika-Shukla** [comment]
@divyanshu-rawat Thank You
Can I close the previous PR #163 and create a new fresh one?

**Comment by divyanshu-rawat** [comment]
it has merged conflicts you can start with fresh one as well.
it depends on you.
Good Luck
