### ISSUE TITLE
Change the text for Systers Open Source mailing list in Contact Us page

### ISSUE THREAD

**Issue by isabelcosta** [systers/systers.github.io#167]
## Description
As a person interested in Systers' Open Source Mailing list,
I need see that the mailing-list is specific to Open Source related topics,
so that I can understand the scope of the emails I'm getting from the Systers Open Source mailing list.

On the [Contact Us](http://systers.io/contactus.html) page, the link for the [Systers' Open Source mailing list](http://systers.org/mailman/listinfo/systers-opensource) has the text "Systers Mailing List". This can be misleading since there is also the [Systers mailing list](http://systers.org/mailman/listinfo/systers), which is not only related to the Open Source community.

In the [Join Systers](http://systers.io/index.html#join-systers) section on the main page it says "systers-dev mailing list", which is also an alternative.

## Mocks

Actual screen:

![image](https://user-images.githubusercontent.com/11148726/38458584-cf2ed796-3a97-11e8-9932-48b3ce24d671.png)

Expected screen:

![image](https://user-images.githubusercontent.com/11148726/38458640-5ecee9e0-3a98-11e8-8b33-9bf49d46d6ec.png)

### Update
- [ ] [/contactus.html](https://github.com/systers/systers.github.io/blob/master/contactus.html) fix text for the mailing list link

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by isabelcosta** [comment]
@sara-02 is this a valid issue? Can I work on this?

**Comment by sara-02** [comment]
@isabelcosta Sure. You can add Syster's open source mailing list as the text instead.

**Comment by isabelcosta** [comment]
Thank you @sara-02. Just a clarification, it's "Systers Open Source mailing list" without the apostrophe character, right?

**Comment by isabelcosta** [comment]
@sara-02 I just noticed that similar to the mailing list, the link to Open Source Slack, also does not specifies that the slack is related to Open Source. I'm saying this because Systers have a slack not related to Open Source also. Is that relevant?

**Comment by sara-02** [comment]
@isabelcosta yes, nice catch.

**Comment by isabelcosta** [comment]
@sara-02 can I also edit that on the PR I sent?

**Comment by sara-02** [comment]
@isabelcosta yes, update the link in the PR, and in the description section, add this issue number as well.
