### ISSUE TITLE
Populating GSoC data on one page

### ISSUE THREAD

**Issue by jericahuang** [systers/systers.github.io#169]
## Description
As a user interested in looking through GSoC participant history,
I need look through them efficiently.

The current setup displays each year's data on a separate HTML page without navigation links to other years. This introduces friction in usability and page navigation. It means more pages that would need to be updated in an issue or PR. 
<img width="401" alt="screen shot 2018-04-19 at 3 59 19 pm" src="https://user-images.githubusercontent.com/8077898/39015270-e03e7eb8-43ea-11e8-8049-70647de602d1.png">
From the usability standpoint, on one of these pages, the user would need to click the browser back button/click on the home logo and then scroll down to the Programs section to access other years. The solution that I'm proposing involves a dropdown form to select a year and updates the table displays after a year is selected. It will be implemented using JavaScript.

## Mocks
New GSoC Page
<img width="715" alt="screen shot 2018-04-19 at 4 01 21 pm" src="https://user-images.githubusercontent.com/8077898/39015293-f383a46c-43ea-11e8-966f-9b84a1c3a962.png">

Updated Home Page
<img width="1209" alt="screen shot 2018-04-19 at 4 06 07 pm" src="https://user-images.githubusercontent.com/8077898/39015524-a26e5cba-43eb-11e8-8b00-a9e08ca08d7f.png">

### Update [Required]
- [ ] index.html
- [ ] gsoc/2009.html (delete)
- [ ] gsoc/2010.html (delete)
- [ ] gsoc/2012.html (delete)
- [ ] gsoc/2013.html (delete)
- [ ] gsoc/2014.html (delete)
- [ ] gsoc/2015.html (delete)
- [ ] gsoc/2016.html (delete)
- [ ] gsoc/2017.html (delete)
### New Page
- [ ] New GSoC participant and project history page

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by divyanshu-rawat** [comment]
I liked the idea it will enhance the user-experience as well.
I am in for this but let's see other mentors opinion on the same @MeepyMay, @Janiceilene , @sara-02, @Tharangi , @ancyp .

**Comment by Vaibhavi24** [comment]
@jericahuang It is a good idea indeed. Will help to give comprehensive info at a glance.
Pls wait for suggestions from the maintainers @MeepyMay @Janiceilene @Tharangi

**Comment by Vertika-Shukla** [comment]
@jericahuang  Even I like the idea. Surely it will provide a great user experience. 
Let's wait for more suggestions from maintainers.

**Comment by Tharangi** [comment]
Sounds good to me...

**Comment by sara-02** [comment]
@BaaniLeen I like you idea, however the current mockup even without the scroll table looks pretty clean. 
@jericahuang Can you create a new mockup with the update comments so can get to see how it will look.
My only concern with using a single table format with scroll ,is that, the list might grow big every year. So we might need some sort of pagination to show maybe only the last 5 years table in single page, and have an option to go to older pages. Like we navigate Github issues, it shows the latest ones on a single page, with option to go to older ones, along with a search bar to go to a specific issue as well.

**Comment by ancyp** [comment]
sounds good.
@jericahuang are you  working on this? 
@divyanshu-rawat can we assign it now or should we wait to hear from Janice?

**Comment by jericahuang** [comment]
<img width="1121" alt="screen shot 2018-05-01 at 3 44 47 pm" src="https://user-images.githubusercontent.com/8077898/39490373-abd54678-4d56-11e8-97d9-76c56ac3cb3f.png">

Here is a mockup combining @BaaniLeen 's and @sara-02 's ideas of having a scrollable tables that display 5 years of data. (in addition to having a specific year selector)

**Comment by sara-02** [comment]
@jericahuang Nice!

**Comment by jericahuang** [comment]
Thanks! Does this mean I can begin the technical implementation?

**Comment by sara-02** [comment]
@jericahuang just keep in mind that the website theme might get a new look based on the finalised mockup that @BaaniLeen and @anumehaagrawal are working on. So try to keep your work as modular as possible so that later on, we don't have to redo it again.

**Comment by jericahuang** [comment]
Will do.

**Comment by AngieSky** [comment]
It looks good @jericahuang! let me know if you need a design meeting with @BaaniLeen  and @anumehaagrawal

**Comment by jericahuang** [comment]
Thanks! Just left a message in their slack channel.

**Comment by ancyp** [comment]
@divyanshu-rawat shall we close this?

**Comment by divyanshu-rawat** [comment]
@ancy yes we can.
