### ISSUE TITLE
Update the README file

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#178]
## Description
As a contributor,
I need update the README File,
so that I can add the new commands required to run the Angular App.

### Update [Required]
- [x] README.md

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.25 hours 

@divyanshu-rawat @Janiceilene @ancyp Can you please assign me this issue to work upon?

**Comment by Janiceilene** [comment]
Assigned to Baani!
