### ISSUE TITLE
Create Contact Us page

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#186]
## Description
As a developer,
I need create a contact us page.

## Mockups
![contact](https://user-images.githubusercontent.com/22029744/40292430-f6a03a36-5ce8-11e8-990c-c9fd4acb05e3.png)

### Update [Required]
- [x] contact
- [x] contact.component.html
- [x] contact.component.scss
- [x] contact.component.ts

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6 hours 

@ancyp @divyanshu-rawat @Janiceilene Can you please assign me the issue :)

**Comment by Janiceilene** [comment]
👍

**Comment by ancyp** [comment]
I feel the image for contact us is not necessary.
<img width="1260" alt="screen shot 2018-05-26 at 8 44 39 pm" src="https://user-images.githubusercontent.com/7522358/40582281-cb0f2332-6125-11e8-8429-c0722138c7be.png">
Just the below contents is enough I feel @Janiceilene ?
<img width="1295" alt="screen shot 2018-05-26 at 8 44 55 pm" src="https://user-images.githubusercontent.com/7522358/40582284-038b3804-6126-11e8-9088-86337bac5923.png">
@BaaniLeen can you arrange the phone icons to be on the same indentation?

**Comment by divyanshu-rawat** [comment]
Yes, I also think so you can arrange the phoen icons in the same indentation.

**Comment by BaaniLeen** [comment]
@Janiceilene @divyanshu-rawat The indentation has been updated in the PR. Can you please approve the same? :)

**Comment by Janiceilene** [comment]
LGTM

**Comment by ancyp** [comment]
@Janiceilene please approve in the actual PR.

**Comment by Janiceilene** [comment]
@ancyp Thanks for catching that!  That's what I get for just clicking on notifications from my email without paying attention.

**Comment by ancyp** [comment]
Doesn't this auto-close when I merged PR?
