### ISSUE TITLE
Create JSON Data Files Using GSOC 2015-2017 data

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#187]
## Description
As a contributor,
I need create JSON Data file for the years of GSoC 2015-2017,
to automate retrieval of data in future use (In the Programs Page).

### Update [Required]
- New data files

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours 

@divyanshu-rawat @ancyp @Janiceilene Can you please assign me this issue. :)

**Comment by sara-02** [comment]
@BaaniLeen Can you update the description as to what these `JSON Data files` will contain. Not the details, but a gist would help. Eg: `As a contributor,
I need create JSON Data files. So that Contributor data, and <> can be loaded from it.`
 IMHO the issue looks incomplete otherwise.

**Comment by sara-02** [comment]
@BaaniLeen The PR got merged, is there any work still left on this issue, or can we close it?

**Comment by BaaniLeen** [comment]
@sara-02 Sure this can be closed :)
