### ISSUE TITLE
Create About Us Page

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#194]
## Description
As a contributor,
I need create an about us page (which can be separate from home page or on the home page itself),
so that users can get information about Systers.

## Mocks
![screen shot 2018-05-31 at 10 54 24 pm](https://user-images.githubusercontent.com/22029744/40797380-9db7930c-6525-11e8-9740-e7a3c10e9f24.png)
The about us info which also includes the map as shown below:
![screen shot 2018-05-31 at 10 54 01 pm](https://user-images.githubusercontent.com/22029744/40797382-9fd654f2-6525-11e8-9d14-b3c2a74efd13.png)

### Update [Required]
- [x] about.component.html
- [ ] about.component.scss
- [ ] about.component.ts

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6 hours 

@ancyp @Janiceilene Can you please assign me this issue to work upon? :)

**Comment by sara-02** [comment]
@BaaniLeen Just a suggestion, it would be great if in the about us, you can have a placeholder `to know more various sub-chapters within Systers, and join a local group check out our communities website.`  With a link to communities portal. Since the portal is not live as of now, you can point to the Github repo and update the link later.

**Comment by BaaniLeen** [comment]
@anumehaagrawal What is the url at which the systers portal will be accessible? :)

**Comment by devshiva619** [comment]
can I work on this? as it is named GSOC so asking. if I can plz do assign me this

**Comment by BaaniLeen** [comment]
@devshiva619 It's an open issue because there is a PR being currently evaluated for this. Give me a couple of minutes, will surely find you a newcomers issue which can be worked upon. :)
