### ISSUE TITLE
Change social icons to Icon Stacked social icons

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#196]
## Description
As a contributor,
I need change social icons to stacked social icons,
so that I can have a better user experience.

## Mocks

Current Mockup : 
![screen shot 2018-05-31 at 11 31 12 pm](https://user-images.githubusercontent.com/22029744/40799275-bce24a1a-652a-11e8-9f75-d4ad56219cf6.png)

Updated Mockup :
![screen shot 2018-05-31 at 11 25 07 pm](https://user-images.githubusercontent.com/22029744/40799283-ca9d5a8c-652a-11e8-94c0-2b627cfe3181.png)

### Update [Required]
- [ ] navbar.component.html
- [ ] navbar.component.scss

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours 

@Janiceilene @ancyp @divyanshu-rawat Can you assign me this issue?

**Comment by devshiva619** [comment]
I would like to work on this.

**Comment by BaaniLeen** [comment]
@devshiva619 This issue needs to be closed, since the new icons do not meet the branding guidelines of the organisations.
