### ISSUE TITLE
Still room for improvement to save data by serving appropriately-sized images

### ISSUE THREAD

**Issue by Geekcoder555** [systers/systers.github.io#204]
## Description
Serve scaled images

Serving appropriately-sized images can save many bytes of data and improve the performance of your webpage, especially on low-powered (eg. mobile) devices.

### Update [Required]
The following images are resized in HTML or CSS. Serving scaled images could save 53.3KiB (58% reduction).

    http://systers.io/images/footer-bars.png is resized in HTML or CSS from 1040x140 to 1350x64. Serving a scaled image could save 44.1KiB (54% reduction).
    http://systers.io/images/medium.png is resized in HTML or CSS from 128x128 to 40x40. Serving a scaled image could save 2.5KiB (90% reduction).
    http://systers.io/images/twitter.png is resized in HTML or CSS from 128x128 to 40x40. Serving a scaled image could save 2.0KiB (90% reduction).
    http://systers.io/images/blogger.png is resized in HTML or CSS from 128x128 to 40x40. Serving a scaled image could save 2.0KiB (90% reduction).
    http://systers.io/images/youtube.png is resized in HTML or CSS from 128x128 to 40x40. Serving a scaled image could save 1.6KiB (90% reduction).
    http://systers.io/images/facebook.png is resized in HTML or CSS from 128x128 to 40x40. Serving a scaled image could save 1.2KiB (90% reduction).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by BaaniLeen** [comment]
@Geekcoder555 In the new codebase on the gsoc18-code branch, the social icons are no longer served from images but from font awesome icons. Can you please change the description according to the new codebase. :)
Also, would you like to work on the issue?

**Comment by BaaniLeen** [comment]
@Geekcoder555 Any updates? Would you like to work on it? :)

**Comment by Geekcoder555** [comment]
@BaaniLeen, firsrly, due to my other commitments I wasn't able to respond and ya I will the update the description and also would like to work on the issue

**Comment by Geekcoder555** [comment]
@ancyp, I would like to work on this issue

**Comment by BaaniLeen** [comment]
@ancyp @bethanyr @Janiceilene Shall I take up this issue since it has been inactive for quite some time?

**Comment by sarnava1** [comment]
@BaaniLeen please assign me this issue.

**Comment by AnjaliGarg13** [comment]
@BaaniLeen can this issue be assigned to me if still available . I'm willing t work on this .

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
