### ISSUE TITLE
Leverage browser caching

### ISSUE THREAD

**Issue by Geekcoder555** [systers/systers.github.io#205]
## Description
Leverage browser caching

Page load times can be significantly improved by asking visitors to save and reuse the files included in your website.

    Reduces page load times for repeat visitors
    Particularly effective on websites where users regularly re-visit the same areas of the website
    Benefit-cost ratio: high
    Access needed

General guidelines for setting expiries:

    Truly static content (global CSS styles, logos, etc.) - access plus 1 year
    Everything else - access plus 1 week

### Update [Required]
Leverage browser caching for the following cacheable resources:

    http://systers.io/images/blogger.png (10 minutes)
    http://systers.io/images/facebook.png (10 minutes)
    http://systers.io/images/favicon.png (10 minutes)
    http://systers.io/images/footer-bars.png (10 minutes)
    http://systers.io/images/medium.png (10 minutes)
    http://systers.io/images/systers-logo.png (10 minutes)
    http://systers.io/images/twitter.png (10 minutes)
    http://systers.io/images/youtube.png (10 minutes)
    http://systers.io/stylesheets/fontawesome-all.css (10 minutes)
    http://systers.io/stylesheets/styles.css (10 minutes)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by BaaniLeen** [comment]
Can you please update the description according to the new codebase in the gsoc18-code branch. We will be using Angular routing to create an SPA, i.e., to keep the navbar and footer as constants. If this issue is still applicable, would you like to work on it? :)

**Comment by BaaniLeen** [comment]
@Geekcoder555 Any updates?

**Comment by bethanyr** [comment]
since we updated how the systers.io website is rendered by switching to an Angular app - I'm not sure this issue is still needed at this time. I am going to close it - we can reopen if it's needed.
