### ISSUE TITLE
Need format HTML code

### ISSUE THREAD

**Issue by pprathameshmore** [systers/systers.github.io#208]
## Description
As a developer,
We need to intend HTML code,
so that I can work on this issue.

## Mocks
![code-format](https://user-images.githubusercontent.com/17108186/41192072-5ed2a3b4-6c16-11e8-8e1b-c58ab435444d.PNG)

### Update [Required]
- All HTML files will be updated.
### Enhancement to Update [Optional]
- All HTML files will be updated.

## Definition of Done
- [x] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1/2 hours 

@Janiceilene

**Comment by BaaniLeen** [comment]
@pprathameshmore Can you please update the description for the gsoc18-code branch, since that has the latest code, and confirm if this issue is still present in that branch.
If yes, @ancyp @divyanshu-rawat @Janiceilene can assign it to you work upon. :)

**Comment by pprathameshmore** [comment]
@BaaniLeen Issue is not present in gsoc18-code branch. Which description should I update?

**Comment by BaaniLeen** [comment]
@pprathameshmore Since this issue is not there in the current code branch, we can close the issue?

**Comment by pprathameshmore** [comment]
@BaaniLeen You said to update the description? Can you tell me exactly what I do?

**Comment by BaaniLeen** [comment]
I had asked to edit the description of the issue you have created by clicking on the edit icon on the right hand side middle of the screen and update it according to the changes wrt the gsoc18-code branch.

**Comment by pprathameshmore** [comment]
@BaaniLeen Okay! I will find another issue!

**Comment by BaaniLeen** [comment]
@pprathameshmore Would you want to work on Issue #213 ?
