### ISSUE TITLE
Fix indentation error

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#213]
## Description
As a contributor,
I need fix an indentation error in the app-routing.module.ts file,
so that I can remove the TSLint errors.

## Mocks
Current Status of the File : 
![screen shot 2018-06-15 at 9 32 22 am](https://user-images.githubusercontent.com/22029744/41449542-4313f30e-707f-11e8-9dfd-8a53088061e3.png)
After Update the file should look like:
![screen shot 2018-06-15 at 9 33 33 am](https://user-images.githubusercontent.com/22029744/41449554-531b0fda-707f-11e8-9c36-329c5fc14182.png)
 
### Update [Required]
- [ ] Remove the tabs from line 9 to 24
- [ ] For every time 2 tabs are removed from a single line, insert two spaces there.
- [ ] In case a single tab is removed, like in case of curly brackets, do not insert any space before them

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.25 hours

**Comment by BaaniLeen** [comment]
@pprathameshmore Would you like to work on the issue?

**Comment by devshiva619** [comment]
@BaaniLeen Hey I am new to this community plz can I work on this ?

**Comment by BaaniLeen** [comment]
Hey @devshiva619 
Let's wait for @pprathameshmore to reply. :)
In case he does not reply for 24 hours, sure we can ask the mentors to assign you the issue to work upon. :)

**Comment by BaaniLeen** [comment]
@devshiva619 Would you like to work on the issue?

**Comment by devshiva619** [comment]
Sure @BaaniLeen

**Comment by BaaniLeen** [comment]
@devshiva619 According to the Systers Open Source workflow, you must ask one of the mentors, @ancyp @divyanshu-rawat @Janiceilene to assign you the issue and once assigned, you can work on the issue and submit the PR. :)
Systers OSS Worklflow : http://systers.io/open-source-workflow

**Comment by devshiva619** [comment]
@divyanshu-rawat can anyone of you please assign me this so that I can work on this issue.

**Comment by ancyp** [comment]
@devshiva619 you can work on it.
@ExactlyMay I still can't find his name on assignees.

**Comment by devshiva619** [comment]
@BaaniLeen hey I am not able to find the file `app-routing.module.ts`, could you helo me find it plz

**Comment by BaaniLeen** [comment]
@devshiva619 Switch to the gsoc18-code branch, and then in the src/app folder you can find it. 
https://github.com/systers/systers.github.io/blob/gsoc18-code/src/app/app-routing.module.ts
Hope that helps :)

**Comment by devshiva619** [comment]
@BaaniLeen I have sent the PR for this 😃
