### ISSUE TITLE
Adding data for membership levels

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/systers.github.io#215]
## Description
As a Systems community member,
I need to see contributors to Systers Open Source projects membership level wise
So that I can identify the contributors.

### Update [Required]
- [ ] contributors.component.ts
- [ ] contrib.ts

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
7 hours 
@Tharangi @kanmodi  Please assign me this issue

**Comment by Tharangi** [comment]
Done
