### ISSUE TITLE
Change all the variable names to camelCase

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#227]
## Description
As a contributor,
I need maintain a uniform standard for naming all the variables using camelCase,
so that I can ensure good code Quality.

Camel case implies that DemoTest becomes demoTest and my_class becomes myClass.

### Update [Required]
- [ ] All files

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by hakabuk** [comment]
Happy to help with this one, if it's up for grabs!

**Comment by BaaniLeen** [comment]
@hakabuk Sure! The issue is up for grabs! Please request the mentors to assign you the issue before you start working on it. :)

**Comment by Tharangi** [comment]
@hakabuk Sure, you can work on this! This issue is assigned to you. :)

**Comment by hakabuk** [comment]
As far as I can see, these changes should only apply to `.js` files, unless I'm missing something? Please verify :) Thanks!

**Comment by shreyateeza** [comment]
@Tharangi Can I work on this issue? Please assign it to me.

**Comment by hakabuk** [comment]
Happy to be unassigned from this one

**Comment by ExactlyMay** [comment]
@hakabuk Okay. I'll ask @shreyateeza to work on it instead.

There's other [available issues here](https://github.com/systers/systers.github.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22Status%3A+Available%22).

**Comment by BaaniLeen** [comment]
@shreyateeza Any updates?

**Comment by shreyateeza** [comment]
@BaaniLeen Excuse me for not informing. I am not working on this. Please unassign me from this issue.

**Comment by aganjali10** [comment]
@BaaniLeen I am a beginner and this is my first time I am trying open source. I am not able to find the variable that needs to be camelcased as all files are either html or css. Can you please help me out.

**Comment by BaaniLeen** [comment]
@aganjali10 Sure! Since all of the code to be worked upon is in the gsoc18-code branch, after you switch there, you can find especially in the Typescript files, the variables defined without camelCase.
eg. in the src/app/newcomers/ folder, in the newcomers.component.ts file, you can see as below:

![screen shot 2018-08-17 at 10 49 08 am](https://user-images.githubusercontent.com/22029744/44249010-8b49a700-a20b-11e8-9e5e-d4644bace866.png)

The highlighted lines have the variables method_details and workflow_stages, which are not in camelCase and these variables are also used in the newcomers.component.html file. You can change them to camel case so that the variable names become methodDetails and workflowStages respectively.

The documentation for the same can be found here:
https://docs.google.com/document/d/18X83wQjltI2PyWmYqNx4cHvGdTBTu2NaWnlIizdsLO8/edit

Also, in case you have any more doubts, join the slack channel #gh-pages.

**Comment by BaaniLeen** [comment]
@aganjali10 Also, before working on an issue make sure you get it assigned to you from the maintainers @systers/maintainers-gh-pages

**Comment by Janiceilene** [comment]
@aganjali10 As soon as you accept the membership invitation to the GH Pages Newcomers team, you can be assigned to this issue.

**Comment by provanni** [comment]
@BaaniLeen If this is still unassigned I would love to do this!

**Comment by Supreme-Kai** [comment]
Hey there! I'd be happy to work on this if it's still up for grabs :)

**Comment by vatsalanarang** [comment]
@BaaniLeen @Janiceilene I want to work with this issue. Please assign it to me if no one is working on it.

**Comment by sebastiaanspeck** [comment]
If there is still work to do, I am willing to pick this up

**Comment by Anam9** [comment]
Hi! Is this still up for grabs? Willing to work on this :)

**Comment by BaaniLeen** [comment]
@Supreme-Kai Would you want to work on this?

**Comment by Akshay1910** [comment]
can i help you??

**Comment by ancyp** [comment]
@vatsalanarang you seem to be the next in line. Do you want to work on it?

**Comment by rhcu** [comment]
Hi BaaniLeen! Seems that this issue was not referenced in PR yet. :) I am new to Systers community and would be happy to try contributing. Can I work on this?

**Comment by AnjaliGarg13** [comment]
Hi @BaaniLeen  . I'm a beginner and am interested to work on this issue if it is still unassigned . Thanks :)

**Comment by Ayush517** [comment]
Hi @BaaniLeen . If this issue is still open, I would like to work on this. If not, can you please let me know some other issues from where I can get started. Thank You

**Comment by vatsalanarang** [comment]
@ancyp yes I want to work on this issue. please assign this to me.

**Comment by ManethKulatunge** [comment]
Hi seeing that this is open, can I claim this issue?

**Comment by AnnaGabriela** [comment]
I'd love to do this. Can someone assign this to me? @BaaniLeen @Tharangi

**Comment by arzoo14** [comment]
@BaaniLeen @Tharangi 
I would like to solve this issue. Can you please assign this to me?

**Comment by dakshaladia** [comment]
I would like to claim and work on this issue. Can you assign it to me?

**Comment by AnjaliSharma1234** [comment]
@BaaniLeen I would like to work on this issue or any other suitable for me. Can you guide me as how to get it assigned?

**Comment by dakshaladia** [comment]
> I would like to claim and work on this issue. Can you assign it to me?

@BaaniLeen hey could you let me know

**Comment by mayburgos** [comment]
@dakshaladia @AnjaliSharma1234 We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
