### ISSUE TITLE
Add slack handles of contributors

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/systers.github.io#228]
## Description
As a Systers Community member
I need to see Slack handles of project contributors
so that I can contact them to clarify any project related matters.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
8 hours 
@Tharangi  @kanmodi  Please assign me this issue

**Comment by kanmodi** [comment]
Assigned!
