### ISSUE TITLE
Add python style guide

### ISSUE THREAD

**Issue by Fenn-CS** [systers/systers.github.io#230]
## Description
We need to add all our styles guides (and in this case the python style guide) to systers.io website 

## Acceptance Criteria
- [x] Add style guide as much information as possible concerning systers python guidelines.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
6 hours

**Comment by ExactlyMay** [comment]
We're updating and moving the Documentation to [DevEnvironments Repo](https://github.com/systers/DevEnvironments) instead.
