### ISSUE TITLE
Add side margins to the FAQ page in sync with  the header

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#243]
## Description
As a contributor,
I need ensure I have adequate margins to the left and right side,
so that I can have a better UI.

## Mocks
Current UI
![screen shot 2018-07-15 at 10 23 33 am](https://user-images.githubusercontent.com/22029744/42730741-b36adb48-8819-11e8-9bf1-179a1f6ceda9.png)
Desirable UI
![screen shot 2018-07-15 at 10 34 24 am](https://user-images.githubusercontent.com/22029744/42730769-b63f4510-881a-11e8-9a6d-23404a4b11c8.png)

### Update [Required]
- [ ] faq.component.html
1) In the line #2 of the file add `<div class=" container box logos mx-auto d-block">` and at the end of the file, add a closing `</div>` tag.
2) Indent the entire file after adding the new div, to ensure proper alignment.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.25 hours

**Comment by aakankshadhurandhar** [comment]
@BaaniLeen i am interested to work in this issue

**Comment by BaaniLeen** [comment]
Please tag the maintainers to assign you the issue using @systers/maintainers-gh-pages . Work on it only after getting the issue assigned to you. :)

**Comment by ancyp** [comment]
You can work on it @aakankshadhurandhar :)

**Comment by BaaniLeen** [comment]
@ancyp Can you assign me this issue?

**Comment by swaybs** [comment]
May I be assigned to this request?

**Comment by Janiceilene** [comment]
@BaaniLeen You're currently assigned to this issue. Do you want it to be reassigned?

**Comment by BaaniLeen** [comment]
@Janiceilene I have created PR #260 to solve it already. @swaybs Can you please look at the other newcomer issues? Thanks! :)
