### ISSUE TITLE
Horizontally align the View Details buttons on Project Page cards

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#245]
## Description
As a contributor,
I need horizontally align the View Details buttons on the cards,
so that I can have a better UI experience.

## Mocks
![screen shot 2018-07-17 at 5 50 19 am](https://user-images.githubusercontent.com/22029744/42789888-6a960632-8985-11e8-8159-1b55c48bdf85.png)

### Update [Required]
- [ ] Update project.component.html and use card-footer, inside which we have the View Details button.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 minutes

@Janiceilene Can you please assign me the issue to work upon? :)

**Comment by kanmodi** [comment]
Assigned! :)

**Comment by BaaniLeen** [comment]
Thanks @kanmodi :)
