### ISSUE TITLE
Update the package.json file

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#246]
## Description
As a contributor,
I need update the package.json file,
so that I can my npm packages can be installed on running the `npm install` command.

### Update [Required]
- [ ] package.json

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour 

@ancyp @bethanyr @Janiceilene Please assign me the issue to work upon :)

**Comment by Janiceilene** [comment]
@ancyp Did you accidentally assign yourself to this issue?

**Comment by BaaniLeen** [comment]
Closing this issue, since @bethanyr mentioned that this need not be updated. It already has mongoose, express, and body-parser packages. :)

**Comment by Janiceilene** [comment]
... Then I accidentally closed it. Whoops!

**Comment by BaaniLeen** [comment]
@ancy @Janiceilene It can be closed, right? Or shall I reopen it again?

**Comment by Janiceilene** [comment]
@baani You can close it if you don't need it! I just accidentally closed it when I tried to comment to Ancy, then reopened. It would be nice if you could link to where you and Bethany had the conversation (just in case anyone is interested later).

**Comment by ancyp** [comment]
This is weird, I tried to assign to @BaaniLeen
