### ISSUE TITLE
Remove hardcoding from the Heroku URL for the API calls

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#269]
## Description
As a contributor,
I need remove the hardcoding from the Heroku URLs especially in the API calls.

### Update [Required]
- [ ] common.service.ts

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by f2015537** [comment]
@Tharangi is this still available?

**Comment by bethanyr** [comment]
@f2015537 - are you interested in working on this issue?

**Comment by f2015537** [comment]
Sorry I just couldn't resist myself :P
