### ISSUE TITLE
Write Angular tests for the new changes.

### ISSUE THREAD

**Issue by bethanyr** [systers/systers.github.io#284]
## Description
As a developer,
I need to ensure that new changes do not break existing functionality,
so that I can confidently add new features.

### Update [Required]
- [ ] unit tests that are in a pending state are fixed so that they pass. (run ng test)
- [ ] E2E tests that are in a pending state are fixed so that they pass. (run ng e2e)
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4 hours

**Comment by tiffany-jao** [comment]
Hoping to claim this issue, if it is still available. Thanks! :)

**Comment by bethanyr** [comment]
Hi @tiffany-jao - yes - you can work on this issue. I'll assign it to you.

**Comment by f2015537** [comment]
Hey @tiffany-jao any progress?

**Comment by tiffany-jao** [comment]
@bethanyr  sound good. thanks! 
@f2015537 I fixed most of the tests - still trying to fix the e2e test and two other tests. (two tests in app.component.spec seem obsolete. may either rewrite or delete them.)
