### ISSUE TITLE
Update the Favicons and the Titles of the App

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#286]
## Description
As a contributor,
I need update the favicons and the titles of the app.

### Update [Required]
- [ ] Add the favicon
- [ ] Update the Title of the app

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 minutes + 20 minutes

@Janiceilene @ancyp Can you please assign me the issue to work upon?

**Comment by daminisatya** [comment]
@Janiceilene I think this issue is good to close?

**Comment by BaaniLeen** [comment]
@daminisatya Done! :)
