### ISSUE TITLE
Update the links 

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#288]
## Description
As a contributor,
I need update the links in the newcomers resources section, as well as make the text on top of the slider images as blank.

### Update [Required]
- [ ] Update the links in the newcomers resources section
- [ ] Make the text on top of the slider images as blank

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1.5 + 0.25 hours 

@Janiceilene @ancyp Can you please assign me the issue? Thanks :)

**Comment by daminisatya** [comment]
@Janiceilene I think the links are still broken. For some reason, systers.io is not available. Is it a good idea to change back to systers.github.io? I sent a quick PR. 

Even the main org details over here need an update?

<img width="1019" alt="screen shot 1940-05-30 at 3 28 09 pm" src="https://user-images.githubusercontent.com/6227784/44395804-a0e70580-a558-11e8-948d-c5f315049355.png">

**Comment by BaaniLeen** [comment]
@daminisatya I created this issue to fix the links which are given on the Newcomers Resources Page on the new Heroku App, i.e. the code on the gsoc18-code branch of the app. The same was fixed through PR #300 .
Can we create a separate issue for the change you are suggesting? @Janiceilene
