### ISSUE TITLE
Update the README file

### ISSUE THREAD

**Issue by BaaniLeen** [systers/systers.github.io#297]
## Description
As a contributor,
I need to update the README file.

### Update [Required]
- [ ] README.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

@bethanyr @ancyp @Janiceilene Can you please assign me the issue? Thanks :)

**Comment by daminisatya** [comment]
@bethanyr I think this issue is good to close?

**Comment by BaaniLeen** [comment]
@daminisatya Done :)
