### ISSUE TITLE
Gsoc links missing

### ISSUE THREAD

**Issue by manmeet0307** [systers/systers.github.io#30]
## Description
As a GSOC aspirant ,I want to see previous year selected projects.
Though the links are provided,but newly open file produces an error.
![image](https://user-images.githubusercontent.com/32425680/34403935-4636300c-ebd1-11e7-8a6c-da0bd36b8f70.png)

## Mocks
Error:

![image](https://user-images.githubusercontent.com/32425680/34403801-7b0a5552-ebd0-11e7-9ff5-370d0dcac1a7.png)

After Updating:
![image](https://user-images.githubusercontent.com/32425680/34403904-1aa9b3be-ebd1-11e7-8a9c-484b82288203.png)

### Update

Update is required in this part of code. 
![image](https://user-images.githubusercontent.com/32425680/34403867-e2ccabc2-ebd0-11e7-9142-0f3bdcea0335.png)

## Estimation
45 minutes required

**Comment by sara-02** [comment]
@manmeet0307 Do you still see this error? If things look good then please close this issue :)

**Comment by MeepyMay** [comment]
It's updated. :) Closing now.
