### ISSUE TITLE
Live Heroku app not working

### ISSUE THREAD

**Issue by sarnava1** [systers/systers.github.io#304]
## Description
As a USER,
I need to visit the live heroku app,
so that I can look into the hosted website.

## Mocks
The link https://systers-github-io.herokuapp.com/ provided is now giving application error.

![githubpagesnotworking](https://user-images.githubusercontent.com/25319565/46230989-ee406900-c387-11e8-8838-1ff77bea49ff.png)

## Acceptance Criteria
Please remove the application error so that viewers can view our website.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by sarnava1** [comment]
@bethanyr I created this is issue because the heroku link was not working.

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
