### ISSUE TITLE
Update server.js to ES6 syntax.

### ISSUE THREAD

**Issue by f2015537** [systers/systers.github.io#307]
## Description
As a developer,
I need update my code,
so that I can make use of latest JavaScript features like promises, chaining and async await .

### Update [Required]
- [ ] server.js

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by anumehaagrawal** [comment]
@f2015537  Assigned to you !

**Comment by f2015537** [comment]
@anumehaagrawal this might take some time because it's a difficult issue. Let us make this issue available for other contributors as well. If I come up with a solution I'll ask you to re-assign it to me.

**Comment by f2015537** [comment]
The nodejs team is still working hard to enable the latest ECMAScript features and are having some problems. This is still an **experimental feature** and can be enabled on **nodejs version 11.0** which is the latest version but **not the LTS version**. Since this codebase does not run on the latest nodejs engine **this issue cannot be solved as of now**.

[More on this topic can be read here](https://nodejs.org/api/esm.html)
