### ISSUE TITLE
Adding concurrently as a Dev dependancy

### ISSUE THREAD

**Issue by f2015537** [systers/systers.github.io#309]
## Description
As a developer,
I need to be able to run the sever and client code using a single command,
for more convenience.

### Update [Required]
- [ ]  package.json
### Enhancement to Update [Optional]
- [ ] It would be great if the documentation could include this new feature

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by f2015537** [comment]
@anumehaagrawal @BaaniLeen @bethanyr @Tharangi claim!

**Comment by BaaniLeen** [comment]
Done!
