### ISSUE TITLE
Clicking on github username does not redirect to the github profile

### ISSUE THREAD

**Issue by f2015537** [systers/systers.github.io#313]
## Description
As a user,
I need be able to check the profile of the person who raised an issue or started a PR.

#### Before clicking
![screenshot from 2018-10-31 01-07-44](https://user-images.githubusercontent.com/19348263/47745331-6b257200-dca9-11e8-898a-819887283847.png)

#### After clicking(the entire template just becomes blank)
![screenshot from 2018-10-31 01-08-38](https://user-images.githubusercontent.com/19348263/47745384-87291380-dca9-11e8-8c0f-ac245f0a7ac9.png)

### Update [Required]
- [ ] newcomers.component.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by BaaniLeen** [comment]
Assigned! :)

**Comment by f2015537** [comment]
Closing this issue now! Refer https://github.com/systers/systers.github.io/pull/350
