### ISSUE TITLE
Admins, maintainers, commiters and improvers are harcoded.

### ISSUE THREAD

**Issue by f2015537** [systers/systers.github.io#314]
## Description
As a user,
I need to be able to see the Admins, maintainers, commiters and improvers  in real time.

## Mocks
![screenshot from 2018-10-31 01-15-10](https://user-images.githubusercontent.com/19348263/47745828-9361a080-dcaa-11e8-9371-9b5a800e4a3a.png)
![screenshot from 2018-10-31 01-15-22](https://user-images.githubusercontent.com/19348263/47745830-93fa3700-dcaa-11e8-9a2a-8f23dea080ed.png)
![screenshot from 2018-10-31 01-15-38](https://user-images.githubusercontent.com/19348263/47745831-9492cd80-dcaa-11e8-8e7f-35a3544ef39a.png)
![screenshot from 2018-10-31 01-15-48](https://user-images.githubusercontent.com/19348263/47745834-952b6400-dcaa-11e8-98f9-1d5cf8a2682a.png)

### Update [Required]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
8 hours

**Comment by BaaniLeen** [comment]
@f2015537 How do you plan to approach solving the issue?

**Comment by f2015537** [comment]
@BaaniLeen I was thinking that we can fetch information about the repo in real time using Github's API. Hardcoded entries will very difficult to maintain as the project scales in my opinion. We need an Angular ninja for this. @sarnava1 @littleBuddhaa you up for this?

**Comment by BaaniLeen** [comment]
@f2015537 True.
How do you plan to solve this? 
The slack handles for every user would ideally be coming through the database which is made from the systers-opensource slack inviter.

**Comment by f2015537** [comment]
@BaaniLeen @littleBuddhaa I'm exploring github's API. Can you guys tell me difference between commiters and imporvers? And @BaaniLeen you are right, getting the slack handles will be a pain. I guess we will have to use the slack api too :( . Seems to be a herculean task as of now. The Github API is driving me crazy.

**Comment by littleBuddhaa** [comment]
@f2015537 I could not understand that either, the difference between improvers and committers. Also I still haven't figured out if we can get the admins, maintainers from github's API

**Comment by f2015537** [comment]
Actually, little @littleBuddhaa the Github API has tons of information. I'm sure we will get whatever we need. We just need to get comfortable with the documentation and what json data is return by the various endpoints. We will also need a github key...I exhausted my limit for today in 30 mins of exploring lol

**Comment by littleBuddhaa** [comment]
@f2015537  thanks, that extension was much needed. To me improvers and Contributors sound the same. 
I guess we'll we should ask @BaaniLeen if we can actually have them under one tag. @f2015537 Also let me know if there is anything corresponding to admins. Or maybe those could be hard coded, because they'll never change. If the api doesn't provide that

**Comment by f2015537** [comment]
@littleBuddhaa see the boolean field named **site_admin** on this endpoint:- 
https://api.github.com/orgs/systers/members

**Comment by littleBuddhaa** [comment]
@f2015537 so there is just one site_admin then, for all syster's repos ?

**Comment by f2015537** [comment]
@littleBuddhaa hmmm interesting, let's wait for what @BaaniLeen has to say. @anumehaagrawal you can help out too!

**Comment by f2015537** [comment]
> @f2015537 so there is just one site_admin then, for all syster's repos ?

yeah I guess. Just @janiceilene

**Comment by littleBuddhaa** [comment]
@f2015537 If you notice, admins and improvers for all projects are same, only the maintainers and committers are changing. If that is the case we only need to deal with these two I guess.

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
