### ISSUE TITLE
PC-Prep Kit is missing from the web-dev javascript tab

### ISSUE THREAD

**Issue by f2015537** [systers/systers.github.io#315]
## Description
As a user,
I need to be able to see all the current projects of the organisation.

### Update [Required]
- [ ] newcomers.component.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by f2015537** [comment]
Maintainers, I am claiming this one!

**Comment by kanmodi** [comment]
Assigned! :)

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
