### ISSUE TITLE
No linting rules on the server side

### ISSUE THREAD

**Issue by f2015537** [systers/systers.github.io#319]
## Description
As a developer,
I need to add linting rules,
so that the code-base is more readable and maintainable.

### Update [Required]
- [ ] Adding ESLint as a dev-dependency.
- [ ] Setting up the configuration for ESLint.
- [ ] Linting all the javascript files based on the above configuration.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by f2015537** [comment]
@BaaniLeen I was kind of confused because Codacy was throwing linting errors on my pull requests and the codes on those errors had ESLint rule names on them. This was happening for the server side code only. So my guess is that the TSLint rules are being enforced on the client side code only (written in typescript) and not on the server side files written in Javascript.

**Comment by f2015537** [comment]
@BaaniLeen do you agree with this ^? If yes, I can start working in either of these 2 directions:-
1) Enforcing TSLint rules on the server side.
2) Adding ESLint on the server side and enforcing ESLint rules on the server side.
It is your call. I'm fine working on either solution.

**Comment by f2015537** [comment]
![screenshot 4](https://user-images.githubusercontent.com/19348263/48629651-37a05280-e9e0-11e8-9120-24abcf299fc3.png)

**Comment by f2015537** [comment]
I think codacy bot for this project has not been configured to work with TSLint hence it is throwing ESlint Errors. **This issue is high priority because it will hinder pull requests made for the server side code.**

**Comment by f2015537** [comment]
@BaaniLeen sorry I was kind of confused because Codacy was throwing linting errors on my pull requests and those errors got fixed when I included a .eslintrc.json file with the rules that were being violated. My guess is that Codacy Bot has been configured to work with ESLint instead of TSLint for this project. I hope I'm making sense.

**Comment by f2015537** [comment]
@BaaniLeen sure! I'll work on option 2. You can expect a PR by tonight.

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
