### ISSUE TITLE
Backend Testing Needed

### ISSUE THREAD

**Issue by f2015537** [systers/systers.github.io#321]
## Description
As a developer,
I need to write tests for automated testing purposes,
so that I can test the app before deploying it .

### Update [Required]
- Test all the routes in the backend using a library like mocha

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by f2015537** [comment]
Maintainers, I am claiming this one!

**Comment by BaaniLeen** [comment]
@f2015537 Assigned!

**Comment by anumehaagrawal** [comment]
@f2015537  Are you working on this ?

**Comment by f2015537** [comment]
Yes @anumehaagrawal. I'm working on this.

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
