### ISSUE TITLE
Delete un-required file

### ISSUE THREAD

**Issue by bhawesh96** [systers/systers.github.io#324]
## Description
As a developer,
I don't need [this un-required file](https://github.com/systers/systers.github.io/blob/develop/%7B%7D)

### Update [Required]
- [ ] Delete https://github.com/systers/systers.github.io/blob/develop/%7B%7D

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.1 hours

**Comment by isunitha98selvan** [comment]
I would like to take this up.
