### ISSUE TITLE
Delete more unused and unrequired files

### ISSUE THREAD

**Issue by sarnava1** [systers/systers.github.io#329]
## Description
As a USER,
I need to delete unrequired and unused files.

## Mocks
The app.component.scss file is empty and hence is not required.

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
0.1 hours

**Comment by anumehaagrawal** [comment]
The {} file has been removed in a previous PR right ?

**Comment by sarnava1** [comment]
Sorry @anumehaagrawal I did not notice that. Actually I messed up things in my terminal and forced pushed things which closed my previous PR too. Trying to make things okay again.

**Comment by sarnava1** [comment]
@anumehaagrawal I have changed the PR description accordingly

**Comment by sarnava1** [comment]
@anumehaagrawal Travis is not passing when I opened the PR. I guess that file needs to be there even if there is no code in it otherwise travis will fail saying that it is unable to find the module. So I am closing this issue.
