### ISSUE TITLE
Github and Medium icons redirect to twitter's account.

### ISSUE THREAD

**Issue by DivyeshPuri** [systers/systers.github.io#335]
## Description
As a developer,
I need to replace the links of Github and Medium with correct links,
so that it redirects users to correct page.

### Update [Required]
- [ ] footer.component.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by DivyeshPuri** [comment]
@BaaniLeen I would like to work on this. Please assign me.

**Comment by kanmodi** [comment]
@DivyeshPuri assigned!
