### ISSUE TITLE
Setting Cursor of pointer type.

### ISSUE THREAD

**Issue by DivyeshPuri** [systers/systers.github.io#338]
## Description
As a developer,
I need set cursor type to pointer,
so that it gives users a hint about card expandable or link nature.

## Mocks
![systers](https://user-images.githubusercontent.com/23422478/50047659-fcc53380-00df-11e9-8f5d-0145ea36fac6.PNG)

### Update [Required]
- [ ] Cursor should be Pointer type.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by DivyeshPuri** [comment]
@BaaniLeen @kanmodi I would like to work on this. Please assign me.

**Comment by anumehaagrawal** [comment]
Assigned !

**Comment by DivyeshPuri** [comment]
@anumehaagrawal Thanks 😄
