### ISSUE TITLE
Repetitive Images in Carousel

### ISSUE THREAD

**Issue by DivyeshPuri** [systers/systers.github.io#339]
## Description
As a developer,
I need to remove the repetitive images,
so that either we can add a new image in replace of these images or to reduce the number of requests
.

## Mocks
![systers](https://user-images.githubusercontent.com/23422478/50047730-64c84980-00e1-11e9-8648-657ac912936d.PNG)

### Update [Required]
- [ ] Remove the repetitive images.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by DivyeshPuri** [comment]
@kanmodi @BaaniLeen I would like to work on this. Please assign me

**Comment by anumehaagrawal** [comment]
Assigned
