### ISSUE TITLE
providing link to contributors thumbnail and not just their name

### ISSUE THREAD

**Issue by littleBuddhaa** [systers/systers.github.io#343]
## Description
As a developer,
I need make the entire image/thumbnail of the contributor as a link,
so that the user can know immediately more info about the contributors is provided.

## Mocks
![screenshot from 2018-12-18 15-08-13](https://user-images.githubusercontent.com/36421943/50145397-7d9a5000-02d7-11e9-8879-e53b92aa8365.png)
as of now, only the names are clickable 

### Update [Required]
- [ ] make the thumbnail a link
### Enhancement to Update [Optional]
- [ ] and hover effect and css

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[1] hours

**Comment by littleBuddhaa** [comment]
@BaaniLeen @anumehaagrawal  I would like to do this please

**Comment by bethanyr** [comment]
@BaaniLeen - should we close this issue based on your comments that it is not providing any further detail on the popup?

@littleBuddhaa - is there additional information that you think would be useful to provide on the popup that isn't already displayed on the page?

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
