### ISSUE TITLE
Past three year's projects in Gsoc section are not shown

### ISSUE THREAD

**Issue by littleBuddhaa** [systers/systers.github.io#346]
## Description
As a developer,
I need make sure the past year 3 years Gsoc projects are visible,
so that users can get the correct information.

## Mocks
![screenshot from 2018-12-18 21-35-09](https://user-images.githubusercontent.com/36421943/50166549-52325800-030d-11e9-8a31-c32685d825e2.png)

### Update [Required]
- [ ] Projects of 2015 visible
- [ ] Projects of 2016 visible 
- [ ] Projects of 2015 visible
## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by littleBuddhaa** [comment]
@BaaniLeen @anumehaagrawal  this section requests data from the systers heroku app , which currently is not working.

**Comment by littleBuddhaa** [comment]
@BaaniLeen you mean instead of fetching it from heroku app we hardcode the details, like the other tables ? 
In that case, where do I get the missing details from  ?

**Comment by littleBuddhaa** [comment]
@BaaniLeen I took the details from http://systers.io/index.html#projects and submitted a PR. Please review.

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
