### ISSUE TITLE
Using Generic Labels in Menu Items

### ISSUE THREAD

**Issue by tetesandra** [systers/systers.github.io#35]
Often, opting for anything less than the most obvious choice or most common primary menu items will frustrate site visitors.

Current Menu
![old](https://user-images.githubusercontent.com/36500441/36300150-4f7a6d12-1300-11e8-876f-8d4e520f00cc.png)

Proposed Menu
![new](https://user-images.githubusercontent.com/36500441/36300165-6170ea78-1300-11e8-85da-661ff21c2205.png)

**Comment by shreyateeza** [comment]
Hey @tetsandra please assign this issue to me!

**Comment by shreyateeza** [comment]
I am working on this issue.

**Comment by prachi1210** [comment]
@nkwate-kazim please go ahead and raise a PR

**Comment by punit-agarwal** [comment]
Can I raise a PR for this?

**Comment by punit-agarwal** [comment]
@shreyateeza @prachi1210

**Comment by nkwate-kazim** [comment]
@prachi1210 , I am on it :smile:

**Comment by shreyateeza** [comment]
@punit-agarwal Feel free to take another issue or create one as @nkwate-kazim is working on this.

**Comment by MeepyMay** [comment]
@tetesandra This isn't following the branding guidelines. Also, please update the issue to include all of the required items from the template.

**Comment by tetesandra** [comment]
@MeepyMay Thanks for pointing me to that. I made the proposal based on what was published at the time. Maybe we should give time for whosoever is doing the job to finish her job then necessary amendments can then be made

**Comment by MeepyMay** [comment]
@tetesandra They are available on the Slack channel. I just posted the file in the #gh-pages channel. Please check there.

I'm closing this issue since it doesn't follow the template.
