### ISSUE TITLE
Filtering by writing name of project does not work properly

### ISSUE THREAD

**Issue by littleBuddhaa** [systers/systers.github.io#355]
## Description
As a user,
I need to see all contributors related to the project if I write name of the project in input box,
so that I can get correct information.

## Mocks
![screenshot from 2019-01-02 19-49-57](https://user-images.githubusercontent.com/36421943/50595852-1f20c480-0ec8-11e9-92eb-887242d04570.png)
![screenshot from 2019-01-02 19-50-13](https://user-images.githubusercontent.com/36421943/50595865-2f38a400-0ec8-11e9-8681-04c8b780a58e.png)
Both results are different.

### Update [Required]
- [ ] correct results are being shown

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by littleBuddhaa** [comment]
@BaaniLeen @anumehaagrawal , searching however works fine if name of contributor is written in input box. **Should we just keep the box for names of people** and the dropdown for the projects? Or would you like both project names and people names to work from the search query ?

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
