### ISSUE TITLE
scroll to top when links in footer are clicked

### ISSUE THREAD

**Issue by littleBuddhaa** [systers/systers.github.io#356]
## Description
As a developer,
I need to scroll to top when footer links are clicked for better user experience,
so that all the changed details of the page are shown to the user.

## Mocks
![scroll_issue](https://user-images.githubusercontent.com/36421943/50601689-f655fa80-0eda-11e9-9216-e65aada5c445.gif)

### Update [Required]
- [ ] scroll to top when these three links in footer are clicked (refer the gif)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by littleBuddhaa** [comment]
@BaaniLeen @anumehaagrawal @bethanyr  I created this issue for better user experience. If you feel its useful please assign it to me.

**Comment by sarnava1** [comment]
@anumehaagrawal @BaaniLeen @bethanyr should we add those pages?? If we do not need to add those pages then @littleBuddhaa's idea is good.

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
