### ISSUE TITLE
Reporting Guidelines file does not exist, so link on CODE_OF_CONDUCT file goes nowhere

### ISSUE THREAD

**Issue by isabelcosta** [systers/systers.github.io#358]
## Description
As a contributor,
I need to have reporting_guidelines.md file on the repo,
so that I can know how to report a Code of Conduct violation.

Link to reporting guidelines on Code of Conduct goes nowhere because the file does not exist

### Update [Required]
- [ ] Create reporting_guidelines.md on root folder, to fix the link that is on code_of_conduct.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by isabelcosta** [comment]
This could be a `first-timers-only` issue :)

**Comment by sarnava1** [comment]
@isabelcosta great issue. Similarly, there are links on the footer which take us nowhere like privacy policy, contribution guidelines and terms and conditions.

**Comment by AyahRamahi** [comment]
Can I work on this ?

**Comment by bethanyr** [comment]
@AyahRamahi - yes you can work on this issue.
