### ISSUE TITLE
Improving Home Page Design

### ISSUE THREAD

**Issue by tetesandra** [systers/systers.github.io#36]
## Description
Unfortunately, a lot of people still judge a book by its cover. You never get a second chance to make a first impression. If a new visitor doesn't like what they see, their knee-jerk reaction is to hit the "back" button. Iincluding a featured image, carousel, or Jumbotron on home with other informations that will inform users about Systers, its activities and give them direction to find what there are looking for will be cool

Proposed Home Page Mockup with Jumbotron:

![home](https://user-images.githubusercontent.com/36500441/36300787-ce02350a-1302-11e8-9e86-a97251f1b011.png)

**Comment by shreyateeza** [comment]
Hi @tetesandra! I would like to take this issue. Please assign it to me. :)

**Comment by shreyateeza** [comment]
I am working on this issue.

**Comment by nkwate-kazim** [comment]
@shreyateeza Not yet since a lot of feedback is still being expected from the community w.r.t. to the design. 
Also I don't have the privilege to assign issues

**Comment by shreyateeza** [comment]
@nkwate-kazim Alright! So it means that we can propose our ideas in the form on issues. Right?

**Comment by tetesandra** [comment]
@shreyateeza , have you read the contributors guide to contributing to this project??

**Comment by shreyateeza** [comment]
@tetesandra Yes of course! I don't see that this has to do anything with my question.

**Comment by tetesandra** [comment]
@shreyateeza , I think @nkwate-kazim  have addressed most of your worries. Adding to that, issues are not just to be opened without following guideline. That is why I sent you the contributors guide so that you be able to judge what to open as an issue. I don't think it would a be nice idea to cluster the issues list with very minor and almost no priority details

**Comment by MeepyMay** [comment]
I'm closing this issue since it doesn't follow the template.
