### ISSUE TITLE
Database is not secure

### ISSUE THREAD

**Issue by f2015537** [systers/systers.github.io#363]
## Description
As a developer,
I need ensure that the database is protected,
so that it can be updated by only users with write access.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] Some strategy to authorize users before giving them write access to the database.
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by anumehaagrawal** [comment]
Assigned !

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
