### ISSUE TITLE
Authenticate Github's api used in Issues section

### ISSUE THREAD

**Issue by littleBuddhaa** [systers/systers.github.io#364]
## Description
As a developer I must authenticate the Github API
so that users can access more number of requests. 
Which can be found here (https://developer.github.com/v3/#rate-limiting)

### Update [Required]
- [ ] increase the number of requests per user 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3  hours

**Comment by kanmodi** [comment]
@littleBuddhaa assigned to you! Share your approach of authentication here

**Comment by ManethKulatunge** [comment]
Can I claim this issue if it is not being handled?

**Comment by littleBuddhaa** [comment]
@ManethKulatunge I am not currently working on it. You may take it up :)

**Comment by ManethKulatunge** [comment]
@littleBuddhaa just needed a little guidance before I start. I get the documentation to a certain degree but does this involve coding on a new file or have you already started on authenticating in any form?

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
