### ISSUE TITLE
Navigation bar should have a different background from the rest of the page

### ISSUE THREAD

**Issue by AvaniVerma** [systers/systers.github.io#365]
## Description
As a user,
I need a cleaner interface,
so that I can easily distinguish the navigation bar from the page contents.

### Enhancement to Update 
- [ ] [Better user interface]
- [ ] [Navigation bar has a darker background than the page contents]
- [ ] [Navigation bar sticks to the top of the page after we scroll past the page height]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by kanmodi** [comment]
Would you like to work on this @AvaniVerma ? Attach mock ups of your proposed design

**Comment by AvaniVerma** [comment]
Sure @kanmodi Give me a few days.

**Comment by mahakmakharia** [comment]
Is the issue still open? I'd like to take it up.

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
