### ISSUE TITLE
heroku app not available

### ISSUE THREAD

**Issue by sunn-e** [systers/systers.github.io#367]
## Description
There's nothing here, yet. 
https://systers-github-io.herokuapp.com/

**Comment by mayburgos** [comment]
We're moving our org to [github.com/anitab-org](github.com/anitab-org). Please check out the [zulip's stream newcomers](https://anitab-org.zulipchat.com/#narrow/stream/223071-newcomers) and create a new topic with your interests. We need a lot of help with updating documentation in the new github repos. :)
