### ISSUE TITLE
Add lang="en"to the html start tag

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#38]
## Description
Sometimes people assume that information about natural language could be inferred from the character encoding. However, a character encoding does not enable unambiguous identification of a natural language: there must be a one-to-one mapping between encoding and language for this inference to work, and there isn't one.

This has to added in all html documents written in English language.

Follow https://github.com/systers/slack-systers/blob/develop/PULL_REQUEST_TEMPLATE.md#description when writing commit message.

## Definition of Done
- [ ] Approval by 1 mentor.

## Estimation
30 to 60 minutes

## Difficulty
first-timers-only

**Comment by punit-agarwal** [comment]
Please check my pull request at https://github.com/systers/systers.github.io/pull/46
Thanks.

**Comment by AnkitKhatri55555** [comment]
can i work on this issue?

**Comment by shreyateeza** [comment]
@punit-agarwal was working on this. If he not working anymore then you can go ahead. :)

**Comment by punit-agarwal** [comment]
@AnkitKhatri55555 you may proceed working on this.
Engaged in semester exams. Will start contributing after exams.

**Comment by sara-02** [comment]
@AnkitKhatri55555 you can check the PR submitted by @punit-agarwal ,we left some reviews, you can use those pointers.
Also, we have duplicate PR for this issue https://github.com/systers/systers.github.io/pull/54 by @Saichethan you can check the reviews there as well.
One word of caution, do not modify the `old.index.html`

**Comment by AnkitKhatri55555** [comment]
het @shreyateeza ,check my PR at #76

**Comment by ananyaarun** [comment]
Can i be assigned this issue ?

**Comment by BaaniLeen** [comment]
@ananyaarun Please request the maintainer by using @systers/maintainers-gh-pages to get the issue assigned. :)

**Comment by Tharangi** [comment]
@ananyaarun are you still interested to work on this?

**Comment by bethanyr** [comment]
this issue applied to the old systers.io site and is no longer needed, so I am closing this issue.

**Comment by sarnava1** [comment]
@bethanyr okay.
