### ISSUE TITLE
Missing content attribute

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#40]
## Description
A meta element with an http-equiv attribute whose value is X-UA-Compatible must have a content attribute. This change is required in some html documents.

Follow https://github.com/systers/slack-systers/blob/develop/PULL_REQUEST_TEMPLATE.md#description when writing commit message.

## Definition of Done
- [ ] Approval by 1 mentor.

## Estimation
30 to 60 minutes

## Difficulty
first-timers-only

**Comment by Janiceilene** [comment]
This change has been made in a new version of the site.
