### ISSUE TITLE
Error: Saw " when expecting an attribute name

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#41]
## Description
Make correction at line 53, column 92 in index.html and in some other html documents.

Follow https://github.com/systers/slack-systers/blob/develop/PULL_REQUEST_TEMPLATE.md#description when writing commit message.

## Mocks
--Not Applicable-

### Update (Required)
- [ ] all HTML files in which this error is there.

## Definition of Done
- [ ] Approval by 1 mentor.

## Estimation
30 to 60 minutes

**Comment by anumehaagrawal** [comment]
Can I work on this ? @prachi1210

**Comment by shreyateeza** [comment]
Yeah sure! You can work on this. And don't forget to reference this issue hile writng PR and follow the commit guidelines. :)

**Comment by Saichethan** [comment]
sry I didn't get then could you be more specific @shreyateeza

**Comment by sara-02** [comment]
> @Saichethan Feel free to take another issue as anumehaagrawal has already submitted a PR regarding this.
@shreyateeza @anumehaagrawal can you please mention the PR number here?

**Comment by shreyateeza** [comment]
@sara-02 the PR is #52

**Comment by Tharangi** [comment]
Closing. This is fixed now.
