### ISSUE TITLE
Missing opening tag (<i>)

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#42]
## Description
Missing opening tag (i) in index.html at line 53 and in some other html documents.

Follow https://github.com/systers/slack-systers/blob/develop/PULL_REQUEST_TEMPLATE.md#description when writing commit message.

## Definition of Done
- [ ] Approval by 1 mentor.

## Estimation
30 to 60 minutes

## Difficulty
first-timers-only

**Comment by prssanna** [comment]
Hi @shreyateeza, I've opened a PR for this issue [here](https://github.com/systers/systers.github.io/pull/48) :)

**Comment by shreyateeza** [comment]
Cool! :+1:

**Comment by Janiceilene** [comment]
This has been fixed in an upcoming version of the website.
