### ISSUE TITLE
Missing closing span tag

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#43]
## Description
Missing closing span tag in some html documents.

Follow https://github.com/systers/slack-systers/blob/develop/PULL_REQUEST_TEMPLATE.md#description when writing commit message.

## Definition of Done
- [ ] Only when issue #42 is merged.
- [ ] Approval by 1 mentor.

## Estimation
30 to 60 minutes

## Difficulty
first-timers-only

**Comment by Janiceilene** [comment]
This has been fixed in a new version of the site.
