### ISSUE TITLE
Add id attribute in replacement of name attribute

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#44]
## Description
The name attribute is obsolete. Consider putting an id attribute on the nearest container instead.

## Definition of Done
- [ ] Approval by 1 mentor.

## Estimation
30 to 60 minutes

## Difficulty
first-timers-only

**Comment by divyanshu-rawat** [comment]
@prachi1210 I guess this issue is already been taken care of correct me if I am wrong:).

**Comment by anumehaagrawal** [comment]
@divyanshu-rawat  Can we close this issue then ?

**Comment by divyanshu-rawat** [comment]
@anumehaagrawal  Yes, for sure we can close this
