### ISSUE TITLE
Add 'Difficulty' section

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#45]
## Description
There should be a separate section showing difficulty of issues in the ISSUE_TEMPLATE.md. It is required because many times label is not tagged to the issue.

## Definition of Done
- [ ] Approval by 1 mentor.

## Estimation
Less than 5 minutes

## Difficulty
first-timers-only

**Comment by sunnyp123** [comment]
Assign this issue to me.

**Comment by shreyateeza** [comment]
@sunnyp123 Feel free to take another issue as already a PR regarding this has been created.

**Comment by MeepyMay** [comment]
Changing the issue template will require a change on every Systers repo. Right now, we are using labels to assign difficulty, not the issue template itself. Thank you for the concern.
