### ISSUE TITLE
Change git instructions text alignment in old index.html

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/systers.github.io#51]
## Description
As a user,
I need change git instructions text alignment in old index.html
so that I can maintain uniformity in the UI.
## Mocks
![screenshot-2018-2-21 systers open source projects by systers](https://user-images.githubusercontent.com/25412153/36470766-0c5f4334-1712-11e8-8c8e-723970f42aac.png)

## Acceptance Criteria
Either padding is added to align it with rest of the text or centralised
### Update [Required]
- [ ] old index.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 minutes

**Comment by Janiceilene** [comment]
The old index.html is part of the previous website and isn't being used anymore.
