### ISSUE TITLE
Homepage: RGSoC 2019 wrong link 

### ISSUE THREAD

**Issue by vigzmv** [systers/systers.github.io#53]
## Description
As a When I click on **2019** under **Rails Girls Summer of Code** on the homepage,
I should be taken to that respective page,
Instead, I am taken to a **404 Not Found** Page.

### Update [Required]
- [ ] Update href value of the related anchor tag. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
Few Minutes.

### This issue is suitable for newcomers. 
Recommended Labels: `Difficulty: EASY`, `First Timers Only`

**Comment by MeepyMay** [comment]
We're removing the RGSoC section instead. Thank you for bringing this to our attention.
