### ISSUE TITLE
Create a separate .github folder for templates of issue, PR, coc, contributing - present in root folder

### ISSUE THREAD

**Issue by simsausaurabh** [systers/systers.github.io#55]
## Description
As an organised open-source-developer, we need to follow certain conventions, for making projects great and awesome.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [X] add a separate .github folder for templates.
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by shreyateeza** [comment]
@simsausaurabh All other systers repo don't have a separate .github folder for this. So I think this should not be an issue. ;)

**Comment by simsausaurabh** [comment]
@shreyateeza It's fine if we are following convention to put them in root directory here, but in more broad scenario it's generally put in a separate ```.github``` folder. I am new to this organisation, please close this issue if it's not really required. Thanks.

**Comment by shreyateeza** [comment]
I am afraid I can't. You have to close it yourself.

**Comment by sara-02** [comment]
@simsausaurabh As pointed by @shreyateeza all Systers project are following the same convention, and not using the `.github` folder. One good reason to do so, is to make these files easier to search for. For people new to Git workflow or Github, they will not know that templates are placed inside the `.github` folder. Unless we make changes in all our `README`s, and development docs. 
So please close this issue by yourself :)

**Comment by sara-02** [comment]
@MeepyMay please close this issue.
