### ISSUE TITLE
Attribute aria-hidden is unnecessary for elements that have attribute hidden

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#58]
## Description
As a user,
I need to do remove `aria-hidden='true'` attribute as it is unnecessary for elements that have attribute hidden or vice-versa,
so that there occurs no such warning while validating the code.

## Mocks
--Not Applicable-

### Update [Required]
- [ ] index.html (line no. 71)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes.

**Comment by shreyateeza** [comment]
@prachi1210 @MeepyMay Please add labels `first-timers-only` and `Difficulty:Easy` to this issue.

**Comment by MeepyMay** [comment]
Please update this as an Agile User Story description + Acceptance Criteria.

**Comment by shreyateeza** [comment]
@MeepyMay you can reopen it. I have done the changes. +1

**Comment by shreyateeza** [comment]
I am working on this issue.

**Comment by shreyateeza** [comment]
@sara-02 @divyanshu-rawat @ancyp I think this issue is now approved by May as she has added a label to it. So can I work on this issue now?
P.S.: I already created a PR for this issue but it got closed later because it didn't follow the Systers Open Source Workflow.

**Comment by divyanshu-rawat** [comment]
Yes, you can work on this issue 👍

**Comment by BaaniLeen** [comment]
@shreyateeza Are you working on this issue? Or is this issue open for all to work upon?

**Comment by shreyateeza** [comment]
@BaaniLeen Sorry couldn't submit the PR on time. 🙈
You can go ahead.

**Comment by BaaniLeen** [comment]
@divyanshu-rawat @ancyp Can we open this issue and also add the first-timers-only label? :)
