### ISSUE TITLE
Error: An img element must have an alt attribute, except under certain conditions

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#59]
## Description
There are missing alt attribute for some img elements (read https://www.w3.org/wiki/HTML/Usage/TextAlternatives.)
As a user,
I have to add the alt attribute,
so that under certain conditions, instead of the image the text shows up.

## Mock
![screenshot from 2018-02-26 09-50-10](https://user-images.githubusercontent.com/30488330/36653382-ce20c832-1ada-11e8-8cd9-7f9a47258e3c.png)

### Update [Required]
- [ ] index.html
- [ ] newcomers.html
- [ ] member-levels.html
- [ ] open-source-workflow.html
- [ ] reporting-guidelines.html
- [ ] contactus.html
- [ ] code-of-conduct.html
- [ ] gsoc/2009.html
- [ ] gsoc/2010.html
- [ ] gsoc/2011.html
- [ ] gsoc/2012.html
- [ ] gsoc/2013.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ] gsoc/2017.html
- [ ] gsoc/2009.html
- [ ] RGSoC/2018.html
- [ ] Outreachy/2017.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
30 to 60 minutes.

**Comment by shreyateeza** [comment]
@MeepyMay @prachi1210 Please label this issue as `first-timers-only` and `Difficulty: Easy`.

**Comment by AnkitKhatri55555** [comment]
hey @shreyateeza , can i work on this issue?

**Comment by simsausaurabh** [comment]
@AnkitKhatri55555 sure go ahead, you can work on this issue.

**Comment by shreyateeza** [comment]
Yes @AnkitKhatri55555, you can work! :)

**Comment by MeepyMay** [comment]
Please update this with a screenshot + Acceptance Criteria.

**Comment by shreyateeza** [comment]
@MeepyMay you can reopen it. I have done the changes. :+1:

**Comment by shreyateeza** [comment]
I am working on this issue.

**Comment by shreyateeza** [comment]
@sara-02 @divyanshu-rawat @ancyp I think this issue is now approved by May as she has added a label to it. So can I work on this issue now?
P.S.: I already created a PR for this issue but it got closed later because it didn't follow the Systers Open Source Workflow.

**Comment by divyanshu-rawat** [comment]
Yes, @shreyateeza you can work on this issue.

**Comment by BaaniLeen** [comment]
@shreyateeza Are you working on this issue? Or is it free to be assigned to anyone? :)

**Comment by shreyateeza** [comment]
@BaaniLeen as it was discussed before to have a separate html file for footer for the pages of systers.io so I thought that this could be implemented during the gsoc coding period. That's why I didn't  work on it.

**Comment by ancyp** [comment]
Yep.
closing this then.
