### ISSUE TITLE
Replace 'Places' with 'Resources'

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#60]
## Description
In http://systers.io/newcomers in the first subheader it is written 'Tutorials and Other Helpful Places' rather it should be 'Tutorials and Other Helpful Resources'. 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
Less than 5 minutes.

**Comment by shreyateeza** [comment]
@MeepyMay @prachi1210 Please label this issue as `first-timers-only` and `Difficulty: Easy`.

**Comment by simsausaurabh** [comment]
@shreyateeza Can I start my contribution with this?

**Comment by shreyateeza** [comment]
@simsausaurabh Yes you can! :smile:
