### ISSUE TITLE
Provide a preview link for the project in README or in the project description.

### ISSUE THREAD

**Issue by simsausaurabh** [systers/systers.github.io#61]
## Description
As a github common practice, we should add preview link for front end projects in the project description or readme itself so that any one can directly look the current stage of the project in preview link.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [X] Add a preview link.
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes.

**Comment by sara-02** [comment]
@simsausaurabh As only the creator of the repo will have right to edit the description, the best approach will be to update the `README.md` file, with the link, and a small description about this project, describing its importance w.r.t all `Systers` project.

**Comment by sara-02** [comment]
@Janiceilene what do you say?
Looks like a good `Documentation` issue, can please add that tag to it.

**Comment by sara-02** [comment]
@simsausaurabh The Description has been updated with the link. 
Also the PR #99 Updates the README with the required info.
So please close this issue now :)

**Comment by simsausaurabh** [comment]
@sara-02 the link provided in README now is the link of local deployment. I am suggesting for the link for remote/upstream deployment.

**Comment by simsausaurabh** [comment]
And we can mention this issue in the respective PR to automatically close it when PR referenced to this issue gets merged. Because the linked PR solves this issue, so it would be conventional to reference rather than closing the issue. Thanks.

**Comment by Janiceilene** [comment]
I added a link to the description of the repo.  Closing the issue.
