### ISSUE TITLE
Text going out of the Box

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#64]
## Description
The text moves out of the box when viewing the open-source-workflow page of the website in mobile or when the window is not viewed in full mode.

## Mocks
1. When viewed in Mobile
![screenshot_2018-02-24-14-37-03](https://user-images.githubusercontent.com/30488330/36629152-1209ca6c-1978-11e8-9ffc-1dc135068fb1.png)
2. When the window is not viewed in full mode
![screenshot from 2018-02-24 15-38-36](https://user-images.githubusercontent.com/30488330/36629235-48d82cb8-1979-11e8-9565-a07ad46cba1d.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 minutes

**Comment by shreyateeza** [comment]
@MeepyMay @prachi1210 Please label this issue as `First Timers Only` and `Difficulty: Easy`.

**Comment by sara-02** [comment]
@shreyateeza You can still go ahead and start working on it :)

**Comment by shreyateeza** [comment]
PR already created. Check #71 :)

**Comment by Tharangi** [comment]
This is fixed in the current version of http://systers.io/open-source-workflow.
