### ISSUE TITLE
Manage the Dropdown Menu

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#65]
## Description
When viewed in mobile, when the Contribute tab is expanded the About Us tab hides. See the screenshot.
As a user, 
I want to rectify it,
so that it doesn't create any confusion.

## Mocks
![screenshot_2018-02-24-14-35-40](https://user-images.githubusercontent.com/30488330/36629577-632e3b94-197d-11e8-9b8c-a8774bbe635e.png)

### Update [Required]
- [ ] index.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 minutes

**Comment by MeepyMay** [comment]
This is missing the Acceptance Criteria section. Please update and thank you!

**Comment by AnkitKhatri55555** [comment]
hey @shreyateeza , i want to work on this. Can i?

**Comment by shreyateeza** [comment]
Feel free to take another issue. I am working on this. :smile:

**Comment by MeepyMay** [comment]
Please include #149 errors in this issue to be inclusive of everything the DropDown Menu needs fixed.

**Comment by shreyateeza** [comment]
@MeepyMay sure! :+1:

**Comment by debanjanah** [comment]
@shreyateeza Please update the description and include the error in this issue that clicking on menu header to hide the drop-down isn't working on mobile devices. Thanks!

**Comment by anumehaagrawal** [comment]
@shreyateeza Any updates ?

**Comment by divyanshu-rawat** [comment]
yup, I agree with the same @debanjanah.
1- clicking on menu header to hide the drop-down isn't working on mobile devices.
2 -When viewed in mobile, when the Contribute tab is expanded the About Us tab hides.

@shreyateeza any progress on this? if not let me know can I assign this issue to someone else?
@anumehaagrawal are you willing to work on this?

**Comment by anumehaagrawal** [comment]
Yes @divyanshu-rawat  I will work on it  if @shreyateeza isnt working on it

**Comment by divyanshu-rawat** [comment]
@anumehaagrawal let's wait till @shreyateeza revert.

**Comment by anumehaagrawal** [comment]
@divyanshu-rawat  Yes :)

**Comment by shreyateeza** [comment]
@anumehaagrawal You can go ahead! 🙈

**Comment by divyanshu-rawat** [comment]
@anumehaagrawal I have assigned this issue to you.

**Comment by divyanshu-rawat** [comment]
Now we are building the new platform so I think we can close it.
