### ISSUE TITLE
BUG: Travis build is failing

### ISSUE THREAD

**Issue by simsausaurabh** [systers/systers.github.io#67]
## Description
I found the below comment on https://github.com/travis-ci/travis-ci/issues/933 which is the main cause of travis build fail.
```
The erroneous Ruby build coincided with a brief GitHub outage, I believe -- my own 
Jenkins server timed out trying to clone some GitHub repos around the same time. 
So I speculate that the Travis worker was scheduled to clone my repo, failed, and 
responded not by aborting the build, but by assuming that since there was no 
.travis.yml available it should default to using Rake?
```

### Update [Required]
- [X] Travis needs to be fixed.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
It will take few hours to understand and fix.

**Comment by MeepyMay** [comment]
Closing. #110 addresses the same problem but is more thorough.
