### ISSUE TITLE
Unnecessary color attribute of main menu 'a' in large scale styling

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/systers.github.io#68]
## Description
Remove the unnecessary color attribute of main menu anchor tag under @media(min 768px) in the stylesheet styles.css on line 175 as it has already been defined on line 65.

## Acceptance Criteria
Stylesheet has no duplicate entries
### Update [Required]
- [ ] styles.css

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
10 minutes

**Comment by sara-02** [comment]
Line numbers requiring the change include:
https://github.com/systers/systers.github.io/blob/master/stylesheets/styles.css#L65
and
https://github.com/systers/systers.github.io/blob/master/stylesheets/styles.css#L175

**Comment by AnkitKhatri55555** [comment]
hey @anumehaagrawal ,my pr at #89

**Comment by adityac8** [comment]
Hey @sara-02 @MeepyMay Is this issue up for working?

**Comment by adityac8** [comment]
@Tharangi  Can I get an update on this. 😄

**Comment by Tharangi** [comment]
@anumehaagrawal, shall we give this to @adityac8 to fix OR will you fix this?

**Comment by anumehaagrawal** [comment]
Yeah we can give it to @adityac8

**Comment by adityac8** [comment]
Thanks @anumehaagrawal @Tharangi 😄

**Comment by BaaniLeen** [comment]
This issue is no longer relevant to the new code.
