### ISSUE TITLE
Merging attributes of the same tag under one curly braces

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/systers.github.io#69]
## Description
The attributes of the same h1,h2 and h3 tags have been defined under different braces in the styles.css file making it difficult to find all the attributes of these tags. They all should be merged under the same braces. Make changes to all other such tags.
## Mocks
h1, h2, h3 {
  font-family: 'Cairo', sans-serif;
  margin-bottom: 0; 
}  Line 268

h1, h2, h3 {
  margin-left: 1rem;
  font-weight: normal;
} Line 289

Can be merged under one tag.

## Acceptance Criteria
All attributes of tags are defined in one place
### Update [Required]
- styles.css

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15 minutes

**Comment by sara-02** [comment]
@anumehaagrawal can please add the line number/s pertaining to this issue.

**Comment by AnkitKhatri55555** [comment]
Hey @anumehaagrawal ,check my pr at #88

**Comment by adityac8** [comment]
Hey @sara-02 @MeepyMay Is this issue up for working?

**Comment by adityac8** [comment]
@Tharangi  Can I get an update on this. 😃

**Comment by Tharangi** [comment]
@anumehaagrawal, shall we give this to @adityac8 to fix OR will you fix this? 

@adityac8, Let's wait for @anumehaagrawal's reply first.

**Comment by anumehaagrawal** [comment]
@Tharangi  This issue has been fixed by @Geekcoder555  at pr #88

**Comment by adityac8** [comment]
@anumehaagrawal PR #88 was closed at it was not assigned to anyone 😺

**Comment by anumehaagrawal** [comment]
@adityac8  Okay then you ca go ahead fixing this issue :)

**Comment by adityac8** [comment]
Thanks @anumehaagrawal @Tharangi 👍

**Comment by BaaniLeen** [comment]
@adityac8 Any update on this issue? Are you working on it or is it free to be assigned to anyone?

**Comment by divyanshu-rawat** [comment]
@adityac8 any update on this?

**Comment by adityac8** [comment]
Hey @BaaniLeen I am working on this one. @divyanshu-rawat I got stuck with my exams and will be generating a PR in a day or two 😄

**Comment by BaaniLeen** [comment]
@divyanshu-rawat @ancyp Can you either approve the PR or close this issue as it wont be relevant to the new codebase?
