### ISSUE TITLE
Updating Systers GitHub site to ABI Identity.

### ISSUE THREAD

**Issue by MeepyMay** [systers/systers.github.io#7]
Here are the following changes needed:

- Background to White #FFFFFF
- Headers changed to Tahoma
- Paragraph text to Calibri
- Header Color to Caribbean: #54BCEB
- All current black text to Rich Black: #101820
- All hyperlinks to Tangerine: #F89728
- All hyperlinks remove underline on hover.
- All hyperlinks color change to Crimson #EF4135 OnHover.
- Left Menu Background to Medium Gray: #888B8D
- GitHub Button (and all buttons) to Sublime #C1D82F 
- Hover Over Button Color to Emerald #00833E 

Any questions about additional actions, colors, etc. please post here with @MeepyMay in the comment.

Currently, Roop is taking over this issue.

**Comment by MeepyMay** [comment]
@Rupinderwadali Please take over this issue. I'll bring up new issues as I see appropriate. Thank you!

**Comment by Rupinderwadali** [comment]
Thanks @MeepyMay. Working on it. Will update you soon.

**Comment by Rupinderwadali** [comment]
Done @MeepyMay . 
Issue #8: Add style in web page 
commit: c3ce9163dfeb9577488792337db923e6a6a8be13

**Comment by Rupinderwadali** [comment]
@MeepyMay Please list out the changes that are still required in the web pages. Should I list out the changes that required on the web page according to me?
