### ISSUE TITLE
Value Error : float 'center' is not a float value 

### ISSUE THREAD

**Issue by shreyateeza** [systers/systers.github.io#70]
## Description
There is a value error in [styles.css](https://github.com/systers/systers.github.io/blob/master/stylesheets/styles.css) at line no. 339 - float center is not a float value. Replace it with appropriate value.
For more details regarding float property, see [here](https://www.w3schools.com/cssref/pr_class_float.asp) 

## Mock
--Not-Applicable-

### Update [Required]
- [ ] style.css

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5 minutes

**Comment by sara-02** [comment]
@shreyateeza Can you point to the line number/s where this error is.

**Comment by shreyateeza** [comment]
@sara-02 The error is in line no. 339. I have updated the comment as well. :+1:

**Comment by shreyateeza** [comment]
@MeepyMay Can you please assign me this issue to work on?

**Comment by BaaniLeen** [comment]
@shreyateeza Would you like to work on this issue? Or is it free to be assigned to anyone? 
Please update! :)

**Comment by shreyateeza** [comment]
I have my end semester exams going on. So its open. 😅

**Comment by divyanshu-rawat** [comment]
@BaaniLeen are you willing to work on this?

**Comment by BaaniLeen** [comment]
@shreyateeza All the best for your exams! :D
@divyanshu-rawat Yes, sure! Can you please assign me the issue? :)

**Comment by divyanshu-rawat** [comment]
@BaaniLeen Issue Assigned 👍

**Comment by BaaniLeen** [comment]
@divyanshu-rawat Can we close the issue since it is no longer applicable?
