### ISSUE TITLE
ERROR : ERR_FILE_NOT_FOUND Google Chrome ,MAC OS

### ISSUE THREAD

**Issue by divyanshu-rawat** [systers/systers.github.io#80]
## Description
Encountering Strange error with every .html file in the project while setting up the development environment of systers Github Pages on MAC OS. 
Browser - Google Chrome Version 64.0.3282.167 (Official Build) (64-bit)
Operating System - macos high Sierra 10.13.3

I have attached mocks of two .html files the same hold true for all .html files
Error : Failed to load resource: net::ERR_FILE_NOT_FOUND

As a user,
The error can be resolved or files are loading if we remove / from the file that we are trying to load.
For instance 
Original HTML - <link rel="stylesheet" href="/stylesheets/styles.css">
Modified HTML - <link rel="stylesheet" href="stylesheets/styles.css">
I am also attaching snapshots signifying working of above mentione snapshots

Alternative Solution - Although, files are loading when we run the same project on localhost.

## Mocks
Mock when we are trying to load without moving / from the   <link rel="stylesheet" href="/stylesheets/styles.css"> in index.html page.

![screen shot 2018-02-25 at 11 07 38 pm](https://user-images.githubusercontent.com/13464678/36647094-c134aa12-1a80-11e8-8040-0a95dbfa7d29.png)

The problem resolves when we load by removing / from the  <link rel="stylesheet" href="/stylesheets/styles.css"> from the index.html.

![screen shot 2018-02-25 at 11 06 58 pm](https://user-images.githubusercontent.com/13464678/36647098-d2122b20-1a80-11e8-9516-461dd4719ffb.png)

Now, it can be seen in the above mock that we have /stylesheets/styles.css loaded.

### Update [Required]
- [ ] [index.html]
- [ ] [code-of-conduct.html]
- [ ] [contactus.html]
- [ ] [member-levels.html]
- [ ] [newcomers.html]
- [ ] [open-source-workflow.html]
- [ ] [reporting-guidelines.html]
- [ ] [gsoc/2009.html]
- [ ] [gsoc/2010.html]
- [ ] [gsoc/2011.html]
- [ ] [gsoc/2012.html]
- [ ] [gsoc/2014.html]
- [ ] [gsoc/2015.html]
- [ ] [gsoc/2016.html]
- [ ] [gsoc/2017.html]
- [ ] [rgsoc/2018.html]
- [ ] [Outreachy/2017.html]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
 40 Minutes

**Comment by shreyateeza** [comment]
Mention the names of all the files as a checklist in Update [Required] of Acceptance Criteria section. :wink:

**Comment by divyanshu-rawat** [comment]
@shreyateeza I have updated the comment as per your suggestions Thanks 👍

**Comment by simsausaurabh** [comment]
This is the issue, thanks for raising the issue. :+1:

**Comment by divyanshu-rawat** [comment]
Even it holds true for Images as well they are also not loading because of the trailing slash.
Same procedure is needed to resolve the same 👍

**Comment by BaaniLeen** [comment]
@divyanshu-rawat Is this issue resolved?
