### ISSUE TITLE
Improving Some Grammatical Errors 

### ISSUE THREAD

**Issue by divyanshu-rawat** [systers/systers.github.io#90]
## Description
I guess we can improve some grammatical errors on the systers official website.
I have made use of Grammarly to point the same
So, As a user, I can help correcting Grammatical errors in systers website. 
So, that I can accomplish a Grammarly correct sentences.

## Mocks
On the second bullet point, one grammatically error is work through some Github Tutorials.

In http://systers.io/newcomers we can help in correcting below-mentioned Grammatically error.

Original Version - After you’ve got a basic understanding of Git, work through some Github Tutorials.
Grammatically Correct Version - After you’ve got a basic understanding of Git, work **go through** some Github Tutorials.

![screen shot 2018-02-26 at 9 54 07 am](https://user-images.githubusercontent.com/13464678/36661219-08440e02-1adb-11e8-8371-59f364bdec6c.png)

On the same page, another Grammatically error is 
Original Version - Wording from Google Code In
Grammatically Correct Version - Wording **of** Google Code In

![screen shot 2018-02-26 at 10 27 11 am](https://user-images.githubusercontent.com/13464678/36662742-b1e38718-1adf-11e8-9d39-f9b4b10b6736.png)

In http://systers.io/member-levels we can help in correcting below-mentioned Grammatically error.

Original Version - Organizational Admin act as quality control for the community. 
Grammatically Correct Version - Organizational Admin **acts** as quality control for the community. 

![screen shot 2018-02-26 at 10 31 55 am](https://user-images.githubusercontent.com/13464678/36663024-836e5146-1ae0-11e8-9d5d-61bc190911a7.png)

Original Version - Organizational Admin have final approval on all matters, including member status
Grammatically Correct Version - Organizational Admin **has** final approval on all matters, including member status.

![screen shot 2018-02-26 at 10 35 43 am](https://user-images.githubusercontent.com/13464678/36663115-d4ed847e-1ae0-11e8-8573-a0659d984511.png)

In http://systers.io/code-of-conduct we can help in correcting below-mentioned Grammatically error.

Original Version - Attempt collaboration before conflict.
Grammatically Correct Version - Attempt collaboration before **a** conflict.

![screen shot 2018-02-26 at 10 37 09 am](https://user-images.githubusercontent.com/13464678/36663216-1ffc3c44-1ae1-11e8-8da6-51fd8fd5a53e.png)

### Update [Required]
- [ ] [Resolving Grammatically Errors Mentioned Above]
- [ ] File newcomers.html Line 81 
- [ ] File newcomers.html Line 98
- [ ] File member-levels.html Line 147
- [ ] File member-levels.html Line 149
- [ ] File code-of-conduct.html Line 97

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
40 Minutes

**Comment by shreyateeza** [comment]
Mention the line no.(s), file name(s) in the Update [Required] of Acceptance Criteria section. It would be easier. :smiley_cat:

**Comment by shreyateeza** [comment]
This would be better - 
Original Version - After you’ve got a basic understanding of Git, **work through** some Github Tutorials.
Grammatically Correct Version - After you’ve got a basic understanding of Git, **go through** some Github Tutorials.

**Comment by divyanshu-rawat** [comment]
@shreyateeza I have updated the issue as per your suggestion thanks 👍

**Comment by sara-02** [comment]
@divyanshu-rawat Since this is documentation issue, I leave it to @Janiceilene where we should take it up or not.

**Comment by divyanshu-rawat** [comment]
No problem :)

**Comment by MeepyMay** [comment]
This is not necessary. Grammarly works well with essays, but has a lot of weaknesses with short-hand and bullet points. [Resource](http://blog.karenwoodward.org/2013/03/review-of-grammarly-strengths-weaknesses.html)
