### ISSUE TITLE
Stylesheets are not linked to html files and images not visible

### ISSUE THREAD

**Issue by AnkitKhatri55555** [systers/systers.github.io#92]
## Description
The stylesheets are not applied to the  html files,and images are also not shown when they are ran locally.
As a user , need to remove the extra slashes in front(provide correct path to stylesheets and images) of the stylesheets link tags and same for images, so that the web page can be viewed in original.(after applying stylesheets).
Changes should be done in stylesheet link tags , footers as well as in all sections where images are involved(ex: logo). 

## Mocks
The web page when without stylesheet linking as well as no images.
![screen shot 1939-12-07 at 4 39 28 pm](https://user-images.githubusercontent.com/36541665/36667424-cd222d8e-1b13-11e8-9a45-da8b0d1a1034.png)

Original Web page after linking stylesheets as well as images:
![screen shot 1939-12-06 at 1 03 07 pm](https://user-images.githubusercontent.com/36541665/36667451-e4bb4336-1b13-11e8-9b53-98386712c37c.png)

## Acceptance Criteria
Link stylesheets to all html files and also images should be visible.
### Update [Required]
- [ ] All HTML files should be modified(remove extra slash in front).
- [ ] The slashes should be removed for the images as well, so that they are visible.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15-20 min

**Comment by divyanshu-rawat** [comment]
@AnkitKhatri55555 
Hi, Ankit Similar issue is already opened by me https://github.com/systers/systers.github.io/issues/80

**Comment by shreyateeza** [comment]
@AnkitKhatri55555 This issue needs to be closed.
