### ISSUE TITLE
Some pages have the same title, so the title cannot be used to distinguish pages.

### ISSUE THREAD

**Issue by Geekcoder555** [systers/systers.github.io#93]
## Description
Some pages have the same title, so the title cannot be used to distinguish pages.
As a user, Title should be different for each page to avoid confusion.

## Mocks
All pages have same title.
![screen shot 1939-12-07 at 5 55 26 pm](https://user-images.githubusercontent.com/36541665/36670422-478494ea-1b1e-11e8-8aad-afbac6db7bca.png)
![screen shot 1939-12-07 at 5 56 09 pm](https://user-images.githubusercontent.com/36541665/36670441-5cea8808-1b1e-11e8-8d29-3067a3496681.png)

## Acceptance Criteria
Each web page should have different titles so that the pages can be distinguished.
### Update [Required]
- [ ]  index.html
- [ ] code-of-conduct.html
- [ ] contactus.html
- [ ] member-levels.html
- [ ] newcomers.html
- [ ] open-source-workflow.html
- [ ] reporting-guidelines.html
- [ ] gsoc/2009.html
- [ ]  gsoc/2010.html
- [ ]  gsoc/2011.html
- [ ]  gsoc/2012.html
- [ ] gsoc/2014.html
- [ ] gsoc/2015.html
- [ ] gsoc/2016.html
- [ ]  gsoc/2017.html
- [ ] RGSoC/2018.html
- [ ] Outreachy/2017.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15-20 min

**Comment by shreyateeza** [comment]
@AnkitKhatri55555 Please create a checklist of all the files that require this change in Update [Required] of Acceptance Criteria section.

**Comment by shreyateeza** [comment]
Already a PR for this has been created. Feel free to take another issue @Vertika-Shukla :)

**Comment by AnkitKhatri55555** [comment]
@shreyateeza , there is no PR yet for this issue

**Comment by AnkitKhatri55555** [comment]
@Vertika-Shukla , you can go ahead

**Comment by Vertika-Shukla** [comment]
@AnkitKhatri55555 Okay! Thank you

**Comment by BaaniLeen** [comment]
Closing the issue since its no longer valid in the new codebase.
