### ISSUE TITLE
This page(contactus.html) contains a link using the tel: protocol. This is not supported by desktop browsers and iPads

### ISSUE THREAD

**Issue by AnkitKhatri55555** [systers/systers.github.io#94]
## Description
This page(contactus.html) contains a link using the tel: protocol. This is not supported by desktop browsers and iPads. 
  | On desktops, laptops and devices without a mobile SIM or Skype an error message is usually displayed:
Chrome on Windows 7/10 does nothing when the link is clicked
Firefox on Windows 7/10 displays the message 'The address wasn't understood'
IE11 on Windows 7 displays the message 'The webpage cannot be displayed'
IE11 on Windows 10 prompts you to search for an app in the Windows Store
Edge on Windows 10 prompts you to search for an app in the Windows Store
Chrome on Mac with OS 10.11 launches Facetime which cannot make phone calls unless it's paired to an iPhone
Safari on Mac with OS 10.11 launches Facetime which cannot make phone calls unless it's paired to an iPhone
Safari on an iPad with iOS 9.1 launches Facetime which cannot make phone calls unless it's paired to an iPhone

As a user, this should be fixed.

## Mocks
![screen shot 1939-12-07 at 6 02 09 pm](https://user-images.githubusercontent.com/36541665/36670745-353f4950-1b1f-11e8-83b7-e1123dfd1a60.png)
## Acceptance Criteria
The tel link should be fixed

### Update [Required]
- [ ] contactus.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by ikbalsingh** [comment]
So, is anyone working or what? Can I work on this @AnkitKhatri55555

**Comment by MeepyMay** [comment]
Please use the template. The description is too long and the Acceptance Criteria isn't thorough.
