### ISSUE TITLE
Suggestion:Identify row and column headers in data tables using TH elements, and mark layout tables with role='presentation'.

### ISSUE THREAD

**Issue by Geekcoder555** [systers/systers.github.io#97]
## Description

Identify row and column headers in data tables using TH elements, and mark layout tables with role='presentation'.

Data tables allow screen reader users to understand column and row relationships. Layout tables read cells as a series of unrelated paragraphs with no tabular structure. Without TH or ROLE, screen readers apply heuristics to decide whether a table is a layout table or data table. These heuristics vary greatly between screen readers, and are affected by browser being used, window size, and font size (so the outcome is very unpredictable without TH or ROLE). If a data table has headers marked up using TD, then change these to TH. If a data table has no headers, add TH elements describing each row and/or column. If the table is only used for layout add role='presentation' to the TABLE element.
Impact on users:

JAWS Reading: Treats tables without TH and ROLE as layout tables if the table contains cells above or below certain pixel sizes. This measurement is affected by browser window size, browser font size, and the browser used.
NVDA Reading: Applies a 'layout table' heuristic to tables without TH and ROLE which varies depending on the browser used and on the window size in some circumstances.
VoiceOver Safari OSX 10.9 Reading: Uses a sophisticated heuristic on tables without TH and ROLE, which is similar (but not identical) to the heuristic used by NVDA with Firefox.

http://systers.io/index.html - Line 92 ,107

## Mocks
![screen shot 1939-12-07 at 6 27 15 pm](https://user-images.githubusercontent.com/36541665/36671722-bcb0839c-1b22-11e8-9934-01a838a36010.png)

## Acceptance Criteria
Identify row and column headers in data tables using TH elements, and mark layout tables with role='presentation'.
### Update [Required]
- [ ] index.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
15-20 min

**Comment by shreyateeza** [comment]
Nice idea @AnkitKhatri55555! But this is a suggestion to give the page a good look. Right?
Things like this can be suggested on the proposal. So I don't think it should be made an issue now. But I surely know that this can be suggested in the proposal.
What do you think? @sara-02?

**Comment by AnkitKhatri55555** [comment]
@shreyateeza , yes i can surely suggest it in the proposal and i can proceed further on this case based upon your suggestions

**Comment by sara-02** [comment]
@AnkitKhatri55555 you can surely add it to your proposal, and this issue can be labeled with the `GSoC2018` tag.

**Comment by Geekcoder555** [comment]
Anyone workin on it?

**Comment by sara-02** [comment]
@BaaniLeen @divyanshu-rawat Is this still valid, and open for others to contribute to? Please help @Geekcoder555

**Comment by bethanyr** [comment]
After the changes to angular for systers.io - I don't think this issue is needed. I'm going to close this issue.
